### PR TITLE
Fix concurrent `SimpleDnsCache.Cleanup` invocation issues

### LINKED ISSUE #4020: During Akka.IO benchmark run, got exception in the output
When getting benchmark table for #4019, in one iteration of total 4800 runs I got the following exception in the console:
```csharp
[ERROR][04.11.2019 8:59:11][Thread 0012][akka://system/system/$a] Collection was modified; enumeration operation may not execute.
Cause: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.SortedSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Akka.IO.SimpleDnsCache.Cache.Cleanup() in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsCache.cs:line 125
   at Akka.IO.SimpleDnsCache.CleanUp() in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsCache.cs:line 84
   at Akka.IO.SimpleDnsManager.Receive(Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsManager.cs:line 63
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorBase.cs:line 158
   at Akka.Actor.ActorCell.ReceiveMessage(Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 177
   at Akka.Actor.ActorCell.Invoke(Envelope envelope) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 83
[ERROR][04.11.2019 8:59:11][Thread 0012][akka://system/system/$c] Object reference not set to an instance of an object.
Cause: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.SortedSet`1.DoRemove(T item)
   at Akka.IO.SimpleDnsCache.Cache.Cleanup() in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsCache.cs:line 129
   at Akka.IO.SimpleDnsCache.CleanUp() in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsCache.cs:line 84
   at Akka.IO.SimpleDnsManager.Receive(Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsManager.cs:line 62
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorBase.cs:line 158
   at Akka.Actor.ActorCell.ReceiveMessage(Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 177
   at Akka.Actor.ActorCell.Invoke(Envelope envelope) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 81
[ERROR][04.11.2019 8:59:11][Thread 0012][akka://system/system/$b] Object reference not set to an instance of an object.
Cause: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.SortedSet`1.Node.RotateRightLeft()
   at System.Collections.Generic.SortedSet`1.Node.Rotate(TreeRotation rotation)
   at System.Collections.Generic.SortedSet`1.DoRemove(T item)
   at Akka.IO.SimpleDnsCache.Cache.Cleanup() in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsCache.cs:line 129
   at Akka.IO.SimpleDnsCache.CleanUp() in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsCache.cs:line 84
   at Akka.IO.SimpleDnsManager.Receive(Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\IO\SimpleDnsManager.cs:line 62
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorBase.cs:line 158
   at Akka.Actor.ActorCell.ReceiveMessage(Object message) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 177
   at Akka.Actor.ActorCell.Invoke(Envelope envelope) in C:\Projects\Upwork\Aaron\Akka.net\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 81
```

It was during one of the runs with 10 000 message count, 10 bytes per message and 3 concurrent clients.

This seems to be some very rare case, but still need to look at this later.

### PR DESCRIPTION
**Pull request by IgorFedchenko**
Close #4020

### CODE REVIEW

File: src/core/Akka/IO/SimpleDnsCache.cs [hunk 1]
```diff
@@ -121,16 +122,20 @@ public Cache Put(Dns.Resolved answer, long ttl)
 
             public Cache Cleanup()
             {
-                var now = _clock();
-                while (_queue.Any() && !_queue.First().IsValid(now))
```
Comment (Aaronontheweb) [inline src/core/Akka/IO/SimpleDnsCache.cs]: Makes sense - `lock` has to go outside of the loop.
