### PR TITLE
Fix DeferAsync async handler nesting bug in CommandAsync

### LINKED ISSUE #7998: DeferAsync with async handler throws 'RunTask calls cannot be nested' when called from CommandAsync
## Bug Description

`DeferAsync` with an async handler throws `System.AggregateException: One or more errors occurred. (RunTask calls cannot be nested)` when called inside a `CommandAsync` handler after an `await`, when there are no pending persist operations.

## Reproduction

Minimal reproduction: https://gist.github.com/fpretorius/960afd4d1c17e606ad836e6ff836f501

The following pattern causes the bug:

```csharp
public class TestActor : ReceivePersistentActor
{
    public override string PersistenceId => "test-actor";

    public TestActor()
    {
        Recover<SnapshotOffer>(_ => { });
        RecoverAny(_ => { });

        CommandAsync<string>(async msg =>
        {
            await Task.Delay(10);  // Any await before DeferAsync

            // BUG: This throws "RunTask calls cannot be nested" 
            // because _pendingInvocations.Count == 0 (no prior Persist calls)
            DeferAsync(msg, async evt =>
            {
                await Task.CompletedTask;
                Sender.Tell("done");
            });
        });
    }
}
```

## Expected Behavior

`DeferAsync` with an async handler should work correctly when called from within a `CommandAsync` handler, regardless of whether there are pending persist operations.

## Actual Behavior

An exception is thrown:
```
System.AggregateException: One or more errors occurred. (RunTask calls cannot be nested)
```

## Root Cause Analysis

In `src/core/Akka.Persistence/Eventsourced.cs`, the async handler version of `DeferAsync` (lines 812-828) has an optimization that immediately executes the handler via `RunTask()` when there are no pending invocations:

```csharp
if (_pendingInvocations.Count == 0)
{
    RunTask(() => handler(evt));  // BUG: Fails if already in RunTask context
}
```

When `DeferAsync` is called from within a `CommandAsync` handler:
1. `CommandAsync` executes via `RunTask()`, setting `_asyncTaskRunning = true`
2. Inside the handler, after an `await`, user calls `DeferAsync(evt, asyncHandler)`
3. Since no `Persist`/`PersistAsync` was called, `_pendingInvocations.Count == 0`
4. `DeferAsync` calls `RunTask(() => handler(evt))`
5. `RunTask` throws `NotSupportedException("RunTask calls cannot be nested")` because `_asyncTaskRunning` is already `true`

## Workaround

Call `PersistAsync` (even with a no-op) before `DeferAsync` to ensure `_pendingInvocations.Count > 0`:

```csharp
CommandAsync<string>(async msg =>
{
    await Task.Delay(10);
    PersistAsync(msg, _ => { });  // Force queuing path
    DeferAsync(msg, async evt => { ... });
});
```

## Notes

- The sync handler version of `DeferAsync` (lines 779-795) is NOT affected because it directly calls `handler(evt)` without `RunTask`
- `PersistAsync` is NOT affected because it always queues to `_pendingInvocations`, never has the immediate execution path

## Environment

- Akka.NET version: 1.5.x (dev branch)
- .NET version: 8.0
- OS: Any

### PR DESCRIPTION
**Pull request by Aaronontheweb**
## Summary

Fixes #7998

- Fixed `DeferAsync` with async handler throwing "RunTask calls cannot be nested" when called from within a `CommandAsync` handler after an `await`, when there are no pending persist operations
- Added regression tests to verify the fix

## Root Cause

The async handler version of `DeferAsync` had an optimization that immediately executed the handler via `RunTask()` when `_pendingInvocations.Count == 0`. When called from within a `CommandAsync` handler (which is already in a `RunTask` context), this caused the nesting exception.

## Fix

Always queue async handlers to `_pendingInvocations` instead of attempting immediate execution. The handler executes via `PeekApplyHandler` after the command handler completes, safely outside any existing `RunTask` context.

## Test plan

- [x] Added regression test for DeferAsync with async handler from CommandAsync (no prior persist)
- [x] Added test for DeferAsync with sync handler from CommandAsync (verify still works)
- [x] Added test for DeferAsync with async handler after PersistAsync (verify queuing path works)
- [x] All persistence tests pass (284 passed, 3 skipped)
- [x] API compatibility tests pass (17 passed)

### CODE REVIEW

File: src/core/Akka.Persistence/Eventsourced.cs [hunk 1]
```diff
@@ -816,15 +816,14 @@ public void DeferAsync<TEvent>(TEvent evt, Func<TEvent, Task> handler)
                 throw new InvalidOperationException("Cannot persist during replay. Events can be persisted when receiving RecoveryCompleted or later.");
             }
 
-            if (_pendingInvocations.Count == 0)
-            {
-                RunTask(() => handler(evt));
```
Comment (Aaronontheweb) [inline src/core/Akka.Persistence/Eventsourced.cs:821]: This was my bad - added this as part of #7937 , but this was wrong

**Review by Aaronontheweb — COMMENTED** [review]
Detailed my changes

**Review by Arkatufus — APPROVED** [review]
LGTM
