### PR TITLE
Fix ByteString.Empty throws when ToArray was called

### LINKED ISSUE #4580: Writing an empty ByteString to an OutputStreamSink closes the underlying stream
- Which Akka.Net version you are using: 1.4.10
- On which platform you are using Akka.Net: Windows 10

This is either a bug of ByteString or OutputStreamSubscriber.
I create a Stream that should handle ByteStrings, the Sink is a named pipe wrapped in an OutputStreamSubscriber:

```
[TestMethod]
public async Task EmptyByteStringCausesPipeToBeClosed()
{
	NamedPipeServerStream serverPipe = new NamedPipeServerStream("uniquepipename", PipeDirection.Out, 1, PipeTransmissionMode.Byte, PipeOptions.Asynchronous, 20, 20);
	Task serverPipeConnectionTask = serverPipe.WaitForConnectionAsync();

	NamedPipeClientStream clientPipe = new NamedPipeClientStream(".", "uniquepipename", PipeDirection.In, PipeOptions.Asynchronous);
	clientPipe.Connect();

	await serverPipeConnectionTask;
	int cnt = 0;

	Task<IOResult> writeToStreamTask = Source.From(Enumerable.Range(0, 100))
		.Select(i => ByteString.FromString(i.ToString()))                          
		.Select(bs => cnt++ == 10 ? ByteString.Empty : bs)
		.ToMaterialized(StreamConverters.FromOutputStream(() => serverPipe), Keep.Right)
		.Run(materializer);

	Task readFromStreamTask = StreamConverters.FromInputStream(() => clientPipe, 1)
		.RunForeach(bs => TestContext.WriteLine(bs.ToString(Encoding.ASCII)), materializer);

	await Task.WhenAll(writeToStreamTask, readFromStreamTask);                       
}
```

The line `.Select(bs => cnt++ == 10 ? ByteString.Empty : bs)` causes the stream to be finished after the 10th byte.
This is because ByteString.Empty.ToArray() throws an Exception which is caught inside class OutputStreamSubscriber, and in the exception handler, the stage is Cancelled and the IOResult is set to failed.

I didn't expect this behaviour, because I would think writing an empty ByteString to a stream should be ok. Is there a reason, why ByteString.Empty.ToArray() throws instead of returning an empty array ? Or should the OutputStreamSubscriber handle this case better ?
The obvious workaround I use is filtering all Empty ByteStrings before sending them to the Sink...

Best regards,
Detlef

### PR DESCRIPTION
**Pull request by Arkatufus**
Closes #4580

The problem was an empty byte array buffer passed into the `CopyTo` function. `CopyTo` failed immediately with an `ArgumentOutOfRangeException`.
Fixed by immediately returning `Array.Empty<byte>()` when `ToArray()` is called on an empty `ByteString`.

### CODE REVIEW

File: src/core/Akka/Util/ByteString.cs [hunk 1]
```diff
@@ -443,6 +443,9 @@ public bool HasSubstring(ByteString other, int index)
         /// <returns>TBD</returns>
         public byte[] ToArray()
         {
+            if (_count == 0)
```
Comment (Aaronontheweb) [inline src/core/Akka/Util/ByteString.cs:446]: LGTM

**Review by Aaronontheweb — APPROVED** [review]
LGTM
