### PR TITLE
Fix `TcpListener` to not stop from accepting further connections on transient accept errors

### LINKED ISSUE #7969: TcpListener terminating with ConnectionAborted error
**Version Information**
Version of Akka.NET? 1.5.52
Which Akka.NET Modules? Core

**Describe the bug**
We encountered surprising termination of the system TcpListener actor in response to what appears to be a prematurely aborted TCP handshake on our production server. Our usage of the Akka.Net TCP system did not account for the possibility of the listener actor abruptly terminating, which resulted in the server becoming completely unresponsive until restarted. The exact (but anonymized) log line logged was

```[ERR akka.tcp://foo@bar/system/IO-TCP/tcp-listener-0] Fatal socket error in TcpListener: ConnectionAborted```

**To Reproduce**
We're working on a repro case for this problem, will update the ticket once we have one.

**Expected behavior**
We expect a bound server socket to remain operational regardless of the behaviour of an individual connection. 

**Actual behavior**
It looks like an aborted TCP connection (i.e. a connection attempt that sends RST before tcp listener has accepted the connection) ends up terminating the server listener actor.

### PR DESCRIPTION
**Pull request by petrikero**
Fixes #7969

## Changes

- Handle more transient errors in the `TcpListener.HandleAccept()`. This fixes the issue of the `TcpListener` stopping accepting any further incoming connections in case of a transient error during accept.
- Be explicit about handling the known fatal errors in `TcpListener.HandleAccept()`.
- Unknown errors are still treated as fatal. Arguably, they could be treated as transient errors but there's some risk in that as well (some additional context at the end of this description).

Disclaimer: I'm not an expert in the domain got help from AI to craft this PR so a thorough review would be appreciated.

## Checklist

For significant changes, please ensure that the following have been completed (delete if not relevant):

* [X] This change follows the [Akka.NET API Compatibility Guidelines](https://getakka.net/community/contributing/api-changes-compatibility.html).
* [X] This change follows the [Akka.NET Wire Compatibility Guidelines](https://getakka.net/community/contributing/wire-compatibility.html).
* [X] I have [reviewed my own pull request](https://getakka.net/community/contributing/index.html#review-your-own-pull-requests).

## Additional notes

- I believe it's possible to work around the issue here by watching the `TcpListener` actor and re-binding on fatal failures, but any active TCP connections would still be terminated if the issue occurs.
- If the `TcpListener` stops on a fatal error, the `Tcp.Unbound` does not seem to be sent. I.e., this code in the `TcpEchoService.Server` sample does not trigger: `Receive<Tcp.Unbound>(_ => _stopCommander?.Tell("Done"));`
- I was not able to find the watch + re-bind pattern (to protect against unexpected termination) from any of the samples or the docs. I suspect many apps running in production might not have this and are thus susceptible.

Regarding whether the unknown errors should be treated as fatal or transient:
- If the errors are treated as fatal, it increases the likelihood of applications being affected by this. It'd make it less likely for production apps to stop accepting incoming connections.
- If the errors are treated as transient, the `TcpListener` can end up in an infinite loop of retrying what is really a fatal error. This prevents the surrounding app from seeing the issue and reacting to it.
- Perhaps a better approach would be to keep retrying on unknown errors for a few seconds and then terminate so the app can detect and handle the error. Anyway, it's outside the context of this PR.

### CODE REVIEW

File: src/core/Akka/IO/TcpListener.cs [hunk 1]
```diff
@@ -289,9 +296,24 @@ private void HandleAccept(SocketAsyncEventArgs saea)
                     Context.System.Scheduler.ScheduleTellOnce(TimeSpan.FromMilliseconds(10), Self,
                         new RetryAccept(saea), ActorRefs.NoSender);
                     break;
+
+                // Fatal errors - the listener socket itself is broken
```
Comment (Aaronontheweb) [inline src/core/Akka/IO/TcpListener.cs:300]: This isn't necessary - this gets handled by the `default` case below.

File: src/core/Akka/IO/TcpListener.cs [hunk 2]
```diff
@@ -289,9 +296,24 @@ private void HandleAccept(SocketAsyncEventArgs saea)
...
+                case SocketError.OperationAborted:
```
Comment (Aaronontheweb) [inline src/core/Akka/IO/TcpListener.cs]: What's the difference between OperationAborted and ConnectionAborted?

File: src/core/Akka/IO/TcpListener.cs [hunk 3]
```diff
@@ -277,10 +277,17 @@ private void HandleAccept(SocketAsyncEventArgs saea)
                     break;
 
                 case SocketError.ConnectionReset:
+                case SocketError.ConnectionAborted:
```
Comment (Aaronontheweb) [inline src/core/Akka/IO/TcpListener.cs:280]: LGTM

File: src/core/Akka/IO/TcpListener.cs (hunk 2 above)
Comment (Aaronontheweb) [reply src/core/Akka/IO/TcpListener.cs]: Reason I'm  asking is that this might be a transient error - I'd want to know the systems-level explanation of the code first though.

**Review by Aaronontheweb — COMMENTED** [review]
Overall looks fine but I left some comments - I'll need to pull up the source and look at the TCP error codes before approving though

File: src/core/Akka/IO/TcpListener.cs (hunk 2 above)
Comment (petrikero) [reply src/core/Akka/IO/TcpListener.cs]: I'm really not an expert on low-level socket code, but my understanding is that `OperationAborted` maps to `WSA_OPERATION_ABORTED`, which indicates that the listener socket (not the incoming connection socket) was closed/disposed/interrupted.

File: src/core/Akka/IO/TcpListener.cs (hunk 1 above)
Comment (petrikero) [reply src/core/Akka/IO/TcpListener.cs:300]: Ok, I merged the code paths under a single `default:` again.

The rationale was to get a different error message for the unexpected messages but the information is in the logged SocketError anyway.

Comment (Aaronontheweb) [reply src/core/Akka/IO/TcpListener.cs:300]: Thank you

File: src/core/Akka/IO/TcpListener.cs (hunk 2 above)
Comment (Aaronontheweb) [reply src/core/Akka/IO/TcpListener.cs]: Ok, that's great to know - I'll pull down the branch and check it out locally but if what you said is true then yes, this is correct.

**Comment by petrikero** [comment]
@Aaronontheweb Just a quick update: we're still seeing this happen about once a week in our production environments. We did deploy a hotfix that restarts the actor when we see this happen, so we're mostly shielded from the impact (all the connections are dropped temporarily but we have a recovery mechanism for that), but it's quite possible that many Akka-using apps don't have this and could be impacted.

**Comment by Aaronontheweb** [comment]
@petrikero I've talked about this with @Arkatufus this morning and we'll do a new v1.5 release with this fix today.

**Review by Aaronontheweb — APPROVED** [review]
LGTM

**Comment by petrikero** [comment]
> @petrikero I've talked about this with @Arkatufus this morning and we'll do a new v1.5 release with this fix today.

I greatly appreciate you handling this so quickly (given the holiday season)!
