### PR TITLE
SAEA already in use error fix

### LINKED ISSUE #4262: Akka.Cluster.Sharding: need to enable remember-entities to work in durable DData mode
As of https://github.com/akkadotnet/akka.net/pull/4255 remember-entities will work inside Akka.Cluster.Sharding with `storage-mode = ddata` - _however_, in the event of a full cluster restart the sharding system won't recover any of its previously remembered entities. This is a bit of a problem.

In order to fix that, we will first need to implement https://github.com/akkadotnet/akka.net/issues/4261 followed by getting all of the DDataDurable_Specs to pass.

### LINKED ISSUE #4264: Akka.IO Bug: An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance
Version: Akka.NET v1.4.0-beta4

```
[ERROR][2/27/2020 2:44:09 AM][Thread 0018][akka://AkkaSpec/system/IO-TCP/$b] "An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.";
Cause: System.InvalidOperationException: "An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.";
   at System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring()
   at System.Net.Sockets.SocketAsyncEventArgs.SetBufferInternal(Byte[] buffer, Int32 offset, Int32 count)
   at Akka.IO.SocketAsyncEventArgsExtensions.SetBuffer(SocketAsyncEventArgs args, IEnumerable`1 dataCollection) in D:\a\1\s\src\core\Akka\IO\SocketEventArgsPool.cs:line 138
   at Akka.IO.TcpConnection.PendingBufferWrite.DoWrite(ConnectionInfo info) in D:\a\1\s\src\core\Akka\IO\TcpConnection.cs:line 943
   at Akka.IO.TcpConnection.DoWrite(ConnectionInfo info, Option`1 write) in D:\a\1\s\src\core\Akka\IO\TcpConnection.cs:line 532
   at Akka.IO.TcpConnection.<>c__DisplayClass27_0.<HandleWriteMessages>b__0(Object message) in D:\a\1\s\src\core\Akka\IO\TcpConnection.cs:line 367
   at Akka.IO.TcpConnection.<>c__DisplayClass23_0.<Connected>b__0(Object message) in D:\a\1\s\src\core\Akka\IO\TcpConnection.cs:line 223
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message) in D:\a\1\s\src\core\Akka\Actor\ActorBase.cs:line 158
   at Akka.Actor.ActorCell.ReceiveMessage(Object message) in D:\a\1\s\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 192
   at Akka.Actor.ActorCell.Invoke(Envelope envelope) in D:\a\1\s\src\core\Akka\Actor\ActorCell.DefaultMessages.cs:line 81
```
Occurs occasionally when running 

https://github.com/akkadotnet/akka.net/blob/97fa6ed92ecb6d4957c403ec512f10128324adbe/src/core/Akka.Tests/IO/TcpIntegrationSpec.cs#L334-L359

### PR DESCRIPTION
**Pull request by IgorFedchenko**
Close #4264

Issue was that after socket operation was completed, we started sending pending packages without setting "Sending" status. So it was only a matter of time when there will be some sender that will send his package at the same time last "pending" package was sent, and we got this error.

Setting "Sending" status in both cases, and all is running smooth.

### CODE REVIEW

File: src/core/Akka/IO/TcpConnection.cs [hunk 1]
```diff
@@ -314,7 +314,12 @@ private Receive HandleWriteMessages(ConnectionInfo info)
                         AcknowledgeSent();
                         
                         // If there is something to send - send it
-                        DoWrite(info, GetAllowedPendingWrite());
+                        var pendingWrite = GetAllowedPendingWrite();
+                        if (pendingWrite.HasValue)
+                        {
+                            SetStatus(ConnectionStatus.Sending);
```
Comment (Aaronontheweb) [inline src/core/Akka/IO/TcpConnection.cs]: LGTM

**Comment by Aaronontheweb** [comment]
## DEV

# Hocon.Tests.Performance.ConfigFallbackLookupSpecs+Lookup_Config_Fallback_2_Deep
__Tests how quickly Config can be looked up from the second fallback__
_3/5/2020 8:55:14 PM_
### System Info
```ini
NBench=NBench, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.2.9200.0
ProcessorCount=2
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2
```

### NBench Settings
```ini
RunMode=Throughput, TestMode=Measurement
NumberOfIterations=13, MaximumRunTime=00:00:01
Concurrent=True
Tracing=True
```

## Data
-------------------

### Totals
|          Metric |           Units |             Max |         Average |             Min |          StdDev |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |          119.00 |          119.00 |          119.00 |            0.00 |
|TotalCollections [Gen1] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalBytesAllocated |           bytes |    5,310,984.00 |    5,310,984.00 |    5,310,984.00 |            0.00 |
|[Counter] LookupFallbackOp |      operations |      196,750.00 |      196,750.00 |      196,750.00 |            0.00 |

### Per-second Totals
|          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |          124.66 |          120.88 |          117.56 |            1.95 |
|TotalCollections [Gen1] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalBytesAllocated |           bytes |    5,563,575.33 |    5,394,822.62 |    5,246,891.64 |       87,096.85 |
|[Counter] LookupFallbackOp |      operations |      206,107.46 |      199,855.87 |      194,375.64 |        3,226.58 |

## This PR
# Hocon.Tests.Performance.ConfigFallbackLookupSpecs+Lookup_Config_Fallback_2_Deep
__Tests how quickly Config can be looked up from the second fallback__
_3/6/2020 4:21:29 PM_
### System Info
```ini
NBench=NBench, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.2.9200.0
ProcessorCount=2
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2
```

### NBench Settings
```ini
RunMode=Throughput, TestMode=Measurement
NumberOfIterations=13, MaximumRunTime=00:00:01
Concurrent=True
Tracing=True
```

## Data
-------------------

### Totals
|          Metric |           Units |             Max |         Average |             Min |          StdDev |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |           62.00 |           62.00 |           62.00 |            0.00 |
|TotalCollections [Gen1] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalBytesAllocated |           bytes |    2,741,976.00 |    2,741,976.00 |    2,741,976.00 |            0.00 |
|[Counter] LookupFallbackOp |      operations |      392,796.00 |      392,796.00 |      392,796.00 |            0.00 |

### Per-second Totals
|          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |           66.21 |           64.54 |           62.97 |            0.94 |
|TotalCollections [Gen1] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalBytesAllocated |           bytes |    2,928,058.20 |    2,854,337.68 |    2,785,044.48 |       41,763.93 |
|[Counter] LookupFallbackOp |      operations |      419,452.81 |      408,892.14 |      398,965.69 |        5,982.80 |

**Comment by Aaronontheweb** [comment]
2x increase in lookup spec, ~40-45% drop in memory usage, 50% drop in Gen 0 GC

**Comment by Aaronontheweb** [comment]
# DEV
# Hocon.Tests.Performance.ConfigFallbackSpecs+Create_Config_Fallback_1_Deep
__Tests how quickly Config can add a single fallback__
_3/5/2020 8:56:15 PM_
### System Info
```ini
NBench=NBench, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.2.9200.0
ProcessorCount=2
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2
```

### NBench Settings
```ini
RunMode=Throughput, TestMode=Measurement
NumberOfIterations=13, MaximumRunTime=00:00:01
Concurrent=True
Tracing=True
```

## Data
-------------------

### Totals
|          Metric |           Units |             Max |         Average |             Min |          StdDev |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |          131.00 |          131.00 |          131.00 |            0.00 |
|TotalCollections [Gen1] |     collections |            4.00 |            4.00 |            4.00 |            0.00 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalBytesAllocated |           bytes |    4,875,368.00 |    4,864,505.23 |    4,863,600.00 |        3,263.86 |
|[Counter] CreateFallbackOp |      operations |       22,989.00 |       22,989.00 |       22,989.00 |            0.00 |

### Per-second Totals
|          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |          133.44 |          130.00 |          127.07 |            1.78 |
|TotalCollections [Gen1] |     collections |            4.07 |            3.97 |            3.88 |            0.05 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalBytesAllocated |           bytes |    4,954,019.27 |    4,827,285.99 |    4,729,038.77 |       64,420.18 |
|[Counter] CreateFallbackOp |      operations |       23,416.39 |       22,813.20 |       22,299.01 |          311.64 |


## This PR
# Hocon.Tests.Performance.ConfigFallbackSpecs+Create_Config_Fallback_1_Deep
__Tests how quickly Config can add a single fallback__
_3/6/2020 4:22:31 PM_
### System Info
```ini
NBench=NBench, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.2.9200.0
ProcessorCount=2
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2
```

### NBench Settings
```ini
RunMode=Throughput, TestMode=Measurement
NumberOfIterations=13, MaximumRunTime=00:00:01
Concurrent=True
Tracing=True
```

## Data
-------------------

### Totals
|          Metric |           Units |             Max |         Average |             Min |          StdDev |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |           51.00 |           51.00 |           51.00 |            0.00 |
|TotalCollections [Gen1] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalBytesAllocated |           bytes |    5,050,200.00 |    5,050,200.00 |    5,050,200.00 |            0.00 |
|[Counter] CreateFallbackOp |      operations |       29,805.00 |       29,805.00 |       29,805.00 |            0.00 |

### Per-second Totals
|          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |           52.57 |           50.30 |           48.72 |            1.19 |
|TotalCollections [Gen1] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalBytesAllocated |           bytes |    5,205,740.77 |    4,981,002.07 |    4,824,433.40 |      118,259.10 |
|[Counter] CreateFallbackOp |      operations |       30,722.96 |       29,396.61 |       28,472.58 |          697.94 |

**Comment by Aaronontheweb** [comment]
Faster parse operation, but the disparity between this PR and dev gets a lot bigger the more fallbacks you add:

# DEV
# Hocon.Tests.Performance.ConfigFallbackSpecs+Create_Config_Fallback_2_Deep
__Tests how quickly Config can add a two fallbacks__
_3/5/2020 8:56:45 PM_
### System Info
```ini
NBench=NBench, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.2.9200.0
ProcessorCount=2
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2
```

### NBench Settings
```ini
RunMode=Throughput, TestMode=Measurement
NumberOfIterations=13, MaximumRunTime=00:00:01
Concurrent=True
Tracing=True
```

## Data
-------------------

### Totals
|          Metric |           Units |             Max |         Average |             Min |          StdDev |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |          124.00 |          124.00 |          124.00 |            0.00 |
|TotalCollections [Gen1] |     collections |            5.00 |            5.00 |            5.00 |            0.00 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalBytesAllocated |           bytes |    5,209,488.00 |    5,209,225.23 |    5,209,120.00 |           84.28 |
|[Counter] CreateFallbackOp |      operations |        7,999.00 |        7,999.00 |        7,999.00 |            0.00 |

### Per-second Totals
|          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |          132.79 |          129.75 |          124.83 |            2.45 |
|TotalCollections [Gen1] |     collections |            5.35 |            5.23 |            5.03 |            0.10 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalBytesAllocated |           bytes |    5,578,277.04 |    5,450,679.28 |    5,244,001.56 |      102,863.28 |
|[Counter] CreateFallbackOp |      operations |        8,565.71 |        8,369.76 |        8,052.41 |          158.01 |

# This PR
# Hocon.Tests.Performance.ConfigFallbackSpecs+Create_Config_Fallback_2_Deep
__Tests how quickly Config can add a two fallbacks__
_3/6/2020 4:23:00 PM_
### System Info
```ini
NBench=NBench, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.2.9200.0
ProcessorCount=2
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2
```

### NBench Settings
```ini
RunMode=Throughput, TestMode=Measurement
NumberOfIterations=13, MaximumRunTime=00:00:01
Concurrent=True
Tracing=True
```

## Data
-------------------

### Totals
|          Metric |           Units |             Max |         Average |             Min |          StdDev |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |           51.00 |           51.00 |           51.00 |            0.00 |
|TotalCollections [Gen1] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalBytesAllocated |           bytes |      946,280.00 |      946,280.00 |      946,280.00 |            0.00 |
|[Counter] CreateFallbackOp |      operations |       14,719.00 |       14,719.00 |       14,719.00 |            0.00 |

### Per-second Totals
|          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |           54.74 |           53.00 |           51.31 |            1.15 |
|TotalCollections [Gen1] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalBytesAllocated |           bytes |    1,015,697.98 |      983,310.10 |      951,997.79 |       21,378.18 |
|[Counter] CreateFallbackOp |      operations |       15,798.77 |       15,294.99 |       14,807.94 |          332.53 |

**Comment by Aaronontheweb** [comment]
And then the biggest winner, a 10-layer-deep `Config` lookup using a `string` (since most commonly used by end-users)

# Hocon.Tests.Performance.ConfigLookupSpec+Config_Lookup_String_10_Deep_throughput
__Tests how quickly Config can perform a 10 deep path lookup using a string path__
_3/5/2020 8:57:15 PM_
### System Info
```ini
NBench=NBench, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null
OS=Microsoft Windows NT 6.2.9200.0
ProcessorCount=2
CLR=4.0.30319.42000,IsMono=False,MaxGcGeneration=2
```

### NBench Settings
```ini
RunMode=Throughput, TestMode=Measurement
NumberOfIterations=13, MaximumRunTime=00:00:01
Concurrent=True
Tracing=True
```

## Data
-------------------

### Totals
|          Metric |           Units |             Max |         Average |             Min |          StdDev |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |          133.00 |          133.00 |          133.00 |            0.00 |
|TotalCollections [Gen1] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalBytesAllocated |           bytes |    4,898,784.00 |    4,898,784.00 |    4,898,784.00 |            0.00 |
|[Counter] LookupOp |      operations |       74,027.00 |       74,027.00 |       74,027.00 |            0.00 |

### Per-second Totals
|          Metric |       Units / s |         Max / s |     Average / s |         Min / s |      StdDev / s |
|---------------- |---------------- |---------------- |---------------- |---------------- |---------------- |
|TotalCollections [Gen0] |     collections |          134.86 |          131.64 |          126.86 |            2.37 |
|TotalCollections [Gen1] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalCollections [Gen2] |     collections |            0.00 |            0.00 |            0.00 |            0.00 |
|TotalBytesAllocated |           bytes |    4,967,256.64 |    4,848,612.01 |    4,672,465.20 |       87,393.84 |
|[Counter] LookupOp |      operations |       75,061.71 |       73,268.84 |       70,607.03 |        1,320.63 |

**Comment by Aaronontheweb** [comment]
That's a about a 3.25x increase in thoughput and we get down to zero allocations when we use a `HoconPath` object on this PR.

Performance numbers look good - need to look at compatibility performance inside Akka.NET integration tests.

**Comment by Aaronontheweb** [comment]
Wrong PR - damnit lol
