### PR TITLE
DispatcherConfigurators, ForkJoinDispatcher, and more

### LINKED ISSUE #607: Add named dispatchers to Akka.Remote and Akka.Cluster
We have a bunch of `todo:`s inside Akka.Remote and Akka.Cluster for using specific, dedicated, named dispatchers.

## Akka.Remote Example

Here's an example inside Akka.Remote (inside `Remote.conf`)

````
### Default dispatcher for the remoting subsystem

    default-remote-dispatcher {
      type = Dispatcher
      executor = "fork-join-executor"
      fork-join-executor {
        # Min number of threads to cap factor-based parallelism number to
        parallelism-min = 2
        parallelism-max = 2
      }
    }
````

And a class that actually depends on it: https://github.com/akkadotnet/akka.net/blob/dev/src%2Fcore%2FAkka.Remote%2FRemoting.cs#L273

```csharp
internal class TransportSupervisor : UntypedActor
    {
        private readonly SupervisorStrategy _strategy = new OneForOneStrategy(3, TimeSpan.FromMinutes(1), exception => Directive.Restart);
        protected override SupervisorStrategy SupervisorStrategy()
        {
            return _strategy;
        }

        protected override void OnReceive(object message)
        {
            PatternMatch.Match(message)
                .With<RegisterTransportActor>(r =>
                {
                    /*
                     * TODO: need to add support for RemoteDispatcher here.
                     * See https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/RemoteSettings.scala#L42 
                     * and https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/Remoting.scala#L95
                     */
                    Sender.Tell(Context.ActorOf(r.Props.WithDeploy(Deploy.Local), r.Name));
                });
        }
    }
```
These need to be backed up by an actual dedicated threadpool dispatcher.

### LINKED ISSUE #629: Memory footprint
I've been profiling the Akka.NET footprint today.
It was not as good as I expected.
We seem to be at about 1300ish bytes per actor when they are fully created.
This is far too expensive.

I found a few problems.

1. Dispatchers are being recreated per actor, so each actor has its own dispatcher..
1. Watchers is eagerly initialized per actor as a HashSet. 
1. Same goes for WhatchedBy
1. Same goes for TerminateQueue

There should be a good amount of bytes to save by fixing the above issues.
e.g. replace hashset to some other structure, or make it lazy initialized or with a lower capacity

### PR DESCRIPTION
**Pull request by Aaronontheweb**
close #629
affects #629
close #607

Added ForkJoinDispatcher, Dispatchers, DispatcherConfigurators, and the ability
for plugins to write their config settings directly into Dispatchers.

### Using ForkJoinDispatcher
So ForkJoinDispatcher is special - it uses [`Helios.Concurrency.DedicatedThreadPool`](https://github.com/helios-io/DedicatedThreadPool) to create a dedicated set of threads for the exclusive use of the actors configured to use a particular `ForkJoinDispatcher` instance. All of the remoting actors depend on the `default-remote-dispatcher` for instance.

Here's how you can create your own ForkJoinDispatcher instances via Config:

```
myapp{
  my-forkjoin-dispatcher{
    type = ForkJoinDispatcher
    throughput = 100
    dedicated-thread-pool{ #settings for Helios.DedicatedThreadPool
      thread-count = 3 #number of threads
      #deadlock-timeout = 3s #optional timeout for deadlock detection
      threadtype = background #values can be "background" or "foreground"
    }
  }
}
}
```

You can then use this specific `ForkJoinDispatcher` instance by configuring specific actors to use it, whether it's via config or the fluent interface on `Props`:

**Config**
```
akka.actor.deploy{
     /myActor1{
       dispatcher = myapp.my-forkjoin-dispatcher
     }
}
```

**Props**
```csharp
var actor = Sys.ActorOf(Props.Create<Foo>().WithDispatcher("myapp.my-forkjoin-dispatcher"));
```

### Dispatchers
We now have a proper implementation of the `Dispatchers` class, which caches configurations for specific dispatchers and ensures that the same `MessageDispatcher` instance is returned each time when an actor requests access to a specific one.

The only exception to this behavior is the `SynchronizedDispatcher` - that particular one returns a new instance every time its called because it's associated with a specific `ExecutionContext`.

But other than that, all dispatchers are now cached and able to be configured independently.

### Remoting and Persistence actors now run on their own ForkJoinDispatcher
All of the system actors needed to support `Akka.Remote` and `Akka.Persistence` now run on their own named `ForkJoinDispatcher` instances, per what's baked into the Akka configuration sections. I've run the test suite probably 30 times now and everything seems to be ok.

### CODE REVIEW

File: src/core/Akka/Dispatch/CachingConfig.cs [hunk 1]
```diff
@@ -0,0 +1,277 @@
...
+    /// <summary>
+    /// INTERNAL API
+    /// 
+    /// A <see cref="CachingConfig"/> is a <see cref="Config"/> that wraps another <see cref="Config"/> and is used to
+    /// cache path lookup and string retrieval, which we happen to do in some critical paths of the actor creation
+    /// and mailbox selection code.
+    /// 
+    /// All other <see cref="Config"/> operations are delegated to the wrapped <see cref="Config"/>.
+    /// </summary>
+    class CachingConfig : Config
```
Comment (rogeralsing) [inline src/core/Akka/Dispatch/CachingConfig.cs]: This should be used carefully as it could interfere with `InjectTopLevelFallback`. where the config might cache a value that is later overridden by a submodule, e.g. remoting/persistence.

Is this handled in the current impl? is this recreated when new fallbacks are applied?

File: src/core/Akka/Dispatch/Dispatchers.cs [hunk 2]
```diff
@@ -186,84 +147,211 @@ public MessageDispatcher DefaultGlobalDispatcher
...
+
+        private MessageDispatcherConfigurator LookupConfigurator(string id)
+        {
+            MessageDispatcherConfigurator configurator;
+            if (!_dispatcherConfigurators.TryGetValue(id, out configurator))
             {
-                var disp = new ThreadPoolDispatcher
+                // It doesn't matter if we create a dispatcher configurator that isn't used due to concurrent lookup.
+                // That shouldn't happen often and in case it does the actual ExecutorService isn't
+                // created until used, i.e. cheap.
```
Comment (rogeralsing) [inline src/core/Akka/Dispatch/Dispatchers.cs]: Isn't this all solved by the `ConcurrentDictionary<.>.GetOrAdd(...)` ?

https://msdn.microsoft.com/en-us/library/ee378676%28v=vs.110%29.aspx

**Comment by rogeralsing** [comment]
Looks great!

Regarding the name `ForkJoinDispatcher` should we stick with that in .NET too?
Pros:
It fills the same purpose as on JVM, so it is familiar.

Cons:
It is familiar but does not behave the same, the `ForkJoinDispatcher` is the fastest on JVM, it is not on .NET (atm).
It really doesn't use Fork-Join mechanics in our case.

This is all I have ;-)

File: src/core/Akka/Dispatch/CachingConfig.cs (hunk 1 above)
Comment (rogeralsing) [inline src/core/Akka/Dispatch/CachingConfig.cs]: We are also passing bits of configurations across the wire, e.g. some deployment primitives holds a `Config` objects.
This _should_ be handled by the surrogate stuff, but I guess we need to make sure?

Comment (Aaronontheweb) [inline src/core/Akka/Dispatch/CachingConfig.cs]: @rogeralsing truth be told, I'm not clear on how canonical Akka handles this. So I came up with my own solution.

Here's what I did:
Have the `Settings` class publish changes to `Dispatchers`
https://github.com/Aaronontheweb/akka.net/blob/dispatcher-squash-timestamp/src/core/Akka/Actor/Settings.cs#L27

And then have `Dispatchers` rebuild its `CachingConfig`:
https://github.com/Aaronontheweb/akka.net/blob/dispatcher-squash-timestamp/src/core/Akka/Dispatch/Dispatchers.cs#L167

This issue came up when I was integrating @Horusiath's latest Akka.Persistence changes. In all other cases when `InjectTopLevelFallback` is called it's done through the `ActorRefProvider` (i.e. in Akka.Remote / Akka.Cluster) but not in Akka.Persistence. So this is the solution I came up with to allow a plugin to inject its own dispatchers into the registry when it gets called.

The only other way of doing this AFAIK would be to scan all of the assemblies loaded into an Akka.NET AppDomain for embedded HOCON files (we would have to standardize the name) and chain all of them at the same time, rather than do it when they're invoked (plugins get invoked after `ActorRefProvider` and after `Dispatchers` is setup, which is what created this problem.)

I think that's what the JVM does and why all of their resource files are found in the same filename and path in each .jar.

File: src/core/Akka/Dispatch/Dispatchers.cs (hunk 2 above)
Comment (Aaronontheweb) [inline src/core/Akka/Dispatch/Dispatchers.cs]: I think so but all of the funky error handling and lookup stuff would have to be done inside a lambda. So I ran with this just because it was easier to debug.

**Comment by Aaronontheweb** [comment]
Regarding the `ForkJoinDispatcher` name: 

¯\_(ツ)_/¯

Doesn't make much of a difference to me - it doesn't use fork-join mechanics, but it's meant to be familiar. I considered calling it `DedicatedThreadPoolDispatcher`.
