### PR TITLE
IActorRef Equals and CompareTo behavior change

### LINKED ISSUE #3781: ActorRefBase.Equals(IActorRef) and ActorRefBase.CompareTo(IActorRef) do not handle null parameters properly
https://github.com/akkadotnet/akka.net/blob/bc5cc65a3dff829cc5844f921826586f828510f5/src/core/Akka/Actor/ActorRef.cs#L347-L361
Both methods do not handle null parameter properly and if the parameter is null, System.NullReferenceException will be thrown on the other.Path property access.

### PR DESCRIPTION
**Pull request by Arkatufus**
Closes #3781

### CODE REVIEW

File: src/core/Akka/Actor/ActorRef.cs [hunk 1]
```diff
@@ -302,9 +302,10 @@ public override string ToString()
         /// <inheritdoc/>
         public override bool Equals(object obj)
         {
-            var other = obj as IActorRef;
-            if (other == null) return false;
-            return Equals(other);
+            if (obj is IActorRef other)
```
Comment (Aaronontheweb) [inline src/core/Akka/Actor/ActorRef.cs]: LGTM

File: src/core/Akka/Actor/ActorRef.cs [hunk 2]
```diff
@@ -325,21 +326,37 @@ public override int GetHashCode()
...
+        /// <param name="other"></param>
+        /// <returns>
+        /// <c>true</c> if this <see cref="IActorRef"/> instance have the same reference 
+        /// as the <paramref name="other"/> instance, if this <see cref="ActorPath"/> of 
+        /// this <see cref="IActorRef"/> instance is equal to the <paramref name="other"/> instance, 
+        /// and <paramref name="other"/> is not <c>null</c>; otherwise <c>false</c>.
+        /// </returns>
         public bool Equals(IActorRef other)
         {
+            if (other is null) return false;
```
Comment (Aaronontheweb) [inline src/core/Akka/Actor/ActorRef.cs]: LGTM
