### PR TITLE
Fix DataEnvelope merge bug

### LINKED ISSUE #4183: Akka.DistributedData Bug: KeyNotFoundException in DataEnvelope
```
[ERROR][01/31/2020 00:24:43][Thread 0006][akka://ClusterSys/user/ddataReplicator] The given key was not present in the dictionary.
Cause: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Akka.DistributedData.Internal.DataEnvelope.Equals(DataEnvelope other)
   at System.Tuple`2.System.Collections.IStructuralEquatable.Equals(Object other, IEqualityComparer comparer)
   at System.Collections.Immutable.ImmutableDictionary`2.Comparers.Equals(HashBucket x, HashBucket y)
   at System.Collections.Immutable.SortedInt32KeyNode`1.SetOrAdd(Int32 key, TValue value, IEqualityComparer`1 valueComparer, Boolean overwriteExistingValue, Boolean& replacedExistingValue, Boolean& mutated)
   at System.Collections.Immutable.SortedInt32KeyNode`1.SetOrAdd(Int32 key, TValue value, IEqualityComparer`1 valueComparer, Boolean overwriteExistingValue, Boolean& replacedExistingValue, Boolean& mutated)
   at System.Collections.Immutable.SortedInt32KeyNode`1.SetOrAdd(Int32 key, TValue value, IEqualityComparer`1 valueComparer, Boolean overwriteExistingValue, Boolean& replacedExistingValue, Boolean& mutated)
   at System.Collections.Immutable.SortedInt32KeyNode`1.SetItem(Int32 key, TValue value, IEqualityComparer`1 valueComparer, Boolean& replacedExistingValue, Boolean& mutated)
   at System.Collections.Immutable.ImmutableDictionary`2.UpdateRoot(SortedInt32KeyNode`1 root, Int32 hashCode, HashBucket newBucket, IEqualityComparer`1 hashBucketComparer)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
   at System.Collections.Immutable.ImmutableDictionary`2.SetItem(TKey key, TValue value)
   at Akka.DistributedData.Replicator.SetData(String key, DataEnvelope envelope)
   at Akka.DistributedData.Replicator.InitRemovedNodePruning()
   at Akka.DistributedData.Replicator.ReceiveRemovedNodePruningTick()
   at Akka.DistributedData.Replicator.<NormalReceive>b__46_25(RemovedNodePruningTick r)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Action`1 , Object[] )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`16.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

Found this in another long-running sample.

_Originally posted by @Aaronontheweb in https://github.com/akkadotnet/akka.net/pull/4178#issuecomment-580525634_

### LINKED ISSUE #4184: Akka.DistributedData Bug: Can't cast  Unable to cast object of type 'PutDeltaOperation[System.String,Akka.DistributedData.Flag]' to type 'Akka.DistributedData.ORDictionary`2[System.String,Akka.DistributedData.Flag]'.
Did find another bug with DData though:

```
[Node #3(third)][WARNING][1/31/2020 8:24:22 PM][Thread 0018][akka.trttl.gremlin.tcp://ReplicatorSpec@localhost:1664/user/replicator] Couldn't process DeltaPropagation from [UniqueAddress: (akka.trttl.gremlin.tcp://ReplicatorSpec@localhost:1663, 1332140628)] due to System.InvalidCastException: Unable to cast object of type 'PutDeltaOperation[System.String,Akka.DistributedData.Flag]' to type 'Akka.DistributedData.ORDictionary`2[System.String,Akka.DistributedData.Flag]'.
[Node #3(third)]   at Akka.DistributedData.ORDictionary`2.Merge(IReplicatedData other) in D:\a\1\s\src\contrib\cluster\Akka.DistributedData\ORDictionary.cs:line 279
[Node #3(third)]   at Akka.DistributedData.Internal.DataEnvelope.Merge(IReplicatedData otherData) in D:\a\1\s\src\contrib\cluster\Akka.DistributedData\Internal\Internal.cs:line 501
[Node #3(third)]   at Akka.DistributedData.Internal.DataEnvelope.Merge(DataEnvelope other) in D:\a\1\s\src\contrib\cluster\Akka.DistributedData\Internal\Internal.cs:line 479
[Node #3(third)]   at Akka.DistributedData.Replicator.Write(String key, DataEnvelope writeEnvelope) in D:\a\1\s\src\contrib\cluster\Akka.DistributedData\Replicator.cs:line 724
[Node #3(third)]   at Akka.DistributedData.Replicator.WriteAndStore(String key, DataEnvelope writeEnvelope, Boolean reply) in D:\a\1\s\src\contrib\cluster\Akka.DistributedData\Replicator.cs:line 679
[Node #3(third)]   at Akka.DistributedData.Replicator.ReceiveDeltaPropagation(UniqueAddress from, Boolean reply, ImmutableDictionary`2 deltas) in D:\a\1\s\src\contrib\cluster\Akka.DistributedData\Replicator.cs:line 969
```

_Originally posted by @Aaronontheweb in https://github.com/akkadotnet/akka.net/pull/4178#issuecomment-581510515_

### PR DESCRIPTION
**Pull request by Aaronontheweb**
close #4184 
close #4183

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Needed https://github.com/akkadotnet/akka.net/pull/4178 pulled in so I can properly figure out how to replicate this.

File: src/contrib/cluster/Akka.DistributedData/ORDictionary.cs [hunk 1]
```diff
@@ -280,7 +280,7 @@ internal ORDictionary(ORSet<TKey> keySet, IImmutableDictionary<TKey, TValue> val
 
         IReplicatedDelta IDeltaReplicatedData.Delta => Delta;
 
-        IReplicatedData IDeltaReplicatedData.MergeDelta(IReplicatedDelta delta) => Merge((IDeltaOperation)delta);
+        IReplicatedData IDeltaReplicatedData.MergeDelta(IReplicatedDelta delta) => MergeDelta((IDeltaOperation)delta);
```
Comment (Aaronontheweb) [inline src/contrib/cluster/Akka.DistributedData/ORDictionary.cs]: This was the fix for #4184 - needed to call `MergeDelta` here rather than `Merge`.

File: src/contrib/cluster/Akka.DistributedData.Tests/ReplicatorSpecs.cs [hunk 2]
```diff
@@ -0,0 +1,203 @@
...
+            _replicator2.Tell(Dsl.Update(KeyI, GSet<string>.Empty, _writeTwo, a => a.Add("a")));
+
+            // wait for write to replicate to all 3 nodes
+            Within(TimeSpan.FromSeconds(5), () =>
+            {
+                foreach(var p in probes)
+                    p.ExpectMsg<Changed>(c => c.Get(KeyI).Elements.ShouldBe(ImmutableHashSet.Create("a")));
+            });
+
+            await Task.Delay(TimeSpan.FromSeconds(1));
```
Comment (Aaronontheweb) [inline src/contrib/cluster/Akka.DistributedData.Tests/ReplicatorSpecs.cs]: Passes when delay is set to 5 seconds, fails with 1 second. This bug must be related to the timing of events and interval-based messages.

**Comment by Aaronontheweb** [comment]
Problem with 

https://github.com/akkadotnet/akka.net/blob/1d5e80d0d229b02336da91c37083636350429a50/src/contrib/cluster/Akka.DistributedData.Tests.MultiNode/ReplicatorSpec.cs#L706-L734

Is caused by the deltas not being calculated correctly. This should be a no-op, instead it's being registered as a legitimate update.

File: src/contrib/cluster/Akka.DistributedData/Replicator.cs [hunk 3]
```diff
@@ -1051,7 +1052,7 @@ private void ReceiveStatus(IImmutableDictionary<string, ByteString> otherDigests
             var otherKeys = otherDigests.Keys.ToImmutableHashSet();
             var myKeys = (totChunks == 1
                     ? _dataEntries.Keys
-                    : _dataEntries.Keys.Where(x => Math.Abs(MurmurHash.StringHash(x)) % totChunks == chunk))
+                    : _dataEntries.Keys.Where(x => Math.Abs(MurmurHash.StringHash(x) % totChunks) == chunk))
```
Comment (Aaronontheweb) [inline src/contrib/cluster/Akka.DistributedData/Replicator.cs]: This was an extremely frustrating issue to find - the `Math.Abs` needed to be called on the results _of the modulus_, not the results of the hash. Otherwise, certain keys ("D8" in this case) would never be included in the gossip reply back for replication.

File: src/contrib/cluster/Akka.DistributedData/Replicator.cs [hunk 4]
```diff
@@ -695,7 +695,11 @@ private DataEnvelope Write(string key, DataEnvelope writeEnvelope)
             var envelope = GetData(key);
             if (envelope != null)
             {
-                if (ReferenceEquals(envelope, writeEnvelope)) return writeEnvelope;
+                if (envelope.Equals(writeEnvelope))
```
Comment (Aaronontheweb) [inline src/contrib/cluster/Akka.DistributedData/Replicator.cs]: Used this to fix bug related to duplicate `Update` events for identical operations in the `ReplicatorSpec` - this needed to be equality by value, not by reference.

File: src/contrib/cluster/Akka.DistributedData/Replicator.cs (hunk 3 above)
Comment (Aaronontheweb) [reply src/contrib/cluster/Akka.DistributedData/Replicator.cs]: Although I kind of goofed here and changed to things at once: this and the way `IsOtherDifferent` is computed using `ByteString`s for digests.

**Comment by Aaronontheweb** [comment]
Looks like, coming full circle here, that `DataEnvelope` doesn't properly factor in versions when determining equality by value - a bug that we missed because we never tested for equality by value in a critical area in the first place.... Right on....

**Comment by Aaronontheweb** [comment]
Ah, no - I take that back. The issue is the `GCounter` by the looks of it.

File: src/contrib/cluster/Akka.DistributedData/GCounter.cs [hunk 5]
```diff
@@ -47,8 +47,6 @@ public sealed class GCounter :
         FastMerge<GCounter>,
         IRemovedNodePruning<GCounter>,
         IEquatable<GCounter>,
-        IComparable<GCounter>,
```
Comment (Aaronontheweb) [inline src/contrib/cluster/Akka.DistributedData/GCounter.cs]: Removed `IComparable<GCounter>` - you can't really compare and order the two since this doesn't take into account the different versions recorded across nodes. Let users extract the underlying `ulong` value if they need that functionality.

**Comment by Aaronontheweb** [comment]
Got the tests passing - turns out the critical fix was that our digests never matched on either side of the transaction due to how Hyperion represented the content slightly differently on each side the wire. Using string-based serialization over the stringified content of the message solves the issue.

**Comment by Aaronontheweb** [comment]
can close https://github.com/akkadotnet/akka.net/issues/4183 too while we're at it.
