### PR TITLE
`Resequencer` should always be a child of the journal actor

### LINKED ISSUE #7480: Akka.Persistence: `Akka.Persistence.Journal.AsyncWriteJournal+Resequencer` is created as a top-level `/user` actor instead of a child of the journal
**Version Information**
Version of Akka.NET? v1.5.36 and earlier
Which Akka.NET Modules? Akka.Peristence and all implementations

**Describe the bug**

While reviewing some of the work we've been doing to help keep Phobos metrics clean, @object observed a massive number of `Akka.Persistence.Journal.AsyncWriteJournal+Resequencer` running around under the `/user` actor hierarchy according to Phobos metrics: https://github.com/petabridge/phobos-issues/issues/86#issuecomment-2608221426

As it turns out, this is indeed a bug - the `Resequencer` is being created in the wrong place: 

https://github.com/akkadotnet/akka.net/blob/759e93f55f66e79d8356f6ad1526144126d0b479/src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs#L84

Now as for why there's such a large number of them, two theories:

1. This actor is getting abused by plugin implementations that create `Resequencer`s on-demand and never terminate them
2. The journal actor is restarting frequently and due to this bug, the old `Resequencer`s are never terminated.

**Expected behavior**

The journal should only need a single `Resequencer` and it should be the journal's child.

**Actual behavior**

YOLO

### PR DESCRIPTION
**Pull request by Aaronontheweb**
## Changes

close #7480 

## Checklist

For significant changes, please ensure that the following have been completed (delete if not relevant):

* [x] This change follows the [Akka.NET API Compatibility Guidelines](https://getakka.net/community/contributing/api-changes-compatibility.html).
* [x] This change follows the [Akka.NET Wire Compatibility Guidelines](https://getakka.net/community/contributing/wire-compatibility.html).
* [x] I have [reviewed my own pull request](https://getakka.net/community/contributing/index.html#review-your-own-pull-requests).
* [x] Design discussion issue #7480

### CODE REVIEW

File: src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs [hunk 1]
```diff
@@ -81,7 +81,7 @@ protected AsyncWriteJournal()
             _replayFilterMaxOldWriters = config.GetInt("replay-filter.max-old-writers", 0);
             _replayDebugEnabled = config.GetBoolean("replay-filter.debug", false);
 
-            _resequencer = Context.System.ActorOf(Props.Create(() => new Resequencer()));
+            _resequencer = Context.ActorOf(Props.Create(() => new Resequencer()), "resequencer");
```
Comment (Aaronontheweb) [inline src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs:84]: Self-explanatory

**Review by Arkatufus — APPROVED** [review]
LGTM
