### PR TITLE
Enhance OpenCircuitException error reporting

### LINKED ISSUE #4314: Akka.Pattern: Pass in clearer error message into OpenCircuitException
Akka.NET Version: 1.4.1-rc1 and later

When an Akka.Persistence journal begins experiencing failures on the database-side of the operation, users begin seeing lots of `OpenCircuitExceptions` appear inside their logs - these errors don't do much to tell the human operators of Akka.NET clusters and applications what is really going on under the covers and what the root cause of the issue is.

If we could add some method overloads to `CircuitBreaker` to make it possible to provide a hint as to what's going on, that would be very useful for operators.

### PR DESCRIPTION
**Pull request by Arkatufus**
Closes #4314

- `CircuitBreaker` remembers the last exception that passes it inside the `LastCaughtException` property. 
  This exception is passed to the `OpenCircuitException` whenever it is thrown.
- Changed the `OpenCircuitException` message when it is thrown because of a half-open circuit breaker state.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
cc @ismaelhamed

**Comment by Arkatufus** [comment]
Would this be enough information? I'm open for adding more if anyone can think of any,

File: src/core/Akka/Pattern/CircuitBreakerState.cs [hunk 1]
```diff
@@ -37,9 +37,9 @@ public Open(CircuitBreaker breaker)
         /// <param name="body">N/A</param>
         /// <exception cref="OpenCircuitException">This exception is thrown automatically since the circuit is open.</exception>
         /// <returns>N/A</returns>
-        public override async Task<T> Invoke<T>(Func<Task<T>> body)
```
Comment (ismaelhamed) [inline src/core/Akka/Pattern/CircuitBreakerState.cs:40]: Watch out, @Horusiath introduced these as part of #3754 , though I've been willing to ask how that works actually.

File: src/core/Akka/Pattern/CircuitBreaker.cs [hunk 2]
```diff
@@ -274,7 +276,7 @@ private void Transition(AtomicState fromState, AtomicState toState)
             if (SwapState(fromState, toState))
             {
                 Debug.WriteLine("Successful transition from {0} to {1}", fromState, toState);
-                toState.Enter();
+                toState.Enter(fromState.LastCaughtException);
```
Comment (ismaelhamed) [inline src/core/Akka/Pattern/CircuitBreaker.cs:279]: Do we need to pass the old exception during the transition? Shouldn't the new transtion start with a clean slate?

File: src/core/Akka/Util/Internal/AtomicState.cs [hunk 3]
```diff
@@ -196,6 +199,8 @@ public void Enter()
     /// </summary>
     public interface IAtomicState
     {
+        Exception LastCaughtException { get; }
```
Comment (ismaelhamed) [inline src/core/Akka/Util/Internal/AtomicState.cs:202]: Since the `CircuitBreaker._currentState` is of type `AtomicState` (not `IAtomicState`) and this is `internal` anyway, we could just make `LastCaughtException` a protected internal field of `AtomicState` instead. Just thinking out loud...

**Comment by ismaelhamed** [comment]
@Arkatufus @Aaronontheweb nice one, this is going to help a lot.

File: src/core/Akka/Pattern/CircuitBreakerState.cs (hunk 1 above)
Comment (Aaronontheweb) [reply src/core/Akka/Pattern/CircuitBreakerState.cs:40]: I'll need to check references to see if this actually gets used anywhere.

File: src/core/Akka/Pattern/CircuitBreaker.cs (hunk 2 above)
Comment (Arkatufus) [reply src/core/Akka/Pattern/CircuitBreaker.cs:279]: No, the last caught exception need to be passed from one state to another, for example, exception caught in open state needs to be passed to the closed state, so that failing fast can report the exception that caused the state to close, same thing with closed to half open.

File: src/core/Akka/Pattern/CircuitBreakerState.cs (hunk 1 above)
Comment (Arkatufus) [reply src/core/Akka/Pattern/CircuitBreakerState.cs:40]: Its fine, the async keyword is just a syntactic sugar, it just flags the compiler that the function uses await and it should optimize it to use them. Since the method doesn't use await, we don't need one.

File: src/core/Akka/Util/Internal/AtomicState.cs (hunk 3 above)
Comment (Arkatufus) [reply src/core/Akka/Util/Internal/AtomicState.cs:202]: LastCaughtException is accessed by the circuit breaker, so it needs to be public, but yeah, it can be moved to `AtomicState`. Actually, `IAtomicState` is an unnescessary abstraction, since the abstract `AtomicState` is enough.

File: src/core/Akka/Pattern/CircuitBreaker.cs (hunk 2 above)
Comment (Arkatufus) [reply src/core/Akka/Pattern/CircuitBreaker.cs:279]: I guess another way of doing this by making `OnFail` and `OnSuccess` callback and store/clear the last caught exception in the circuit breaker class instead, do you think that'll be cleaner?

File: src/core/Akka/Pattern/CircuitBreakerState.cs (hunk 1 above)
Comment (Arkatufus) [reply src/core/Akka/Pattern/CircuitBreakerState.cs:40]: By the way, you can use the async version by passing a `Func` that produces a task into a circuit breaker like this:
```
await _circuitBreaker.WithCircuitBreaker(() => MyTask);
```
currently, it accepts `Func<Task>` and `Func<Task<T>`

File: src/core/Akka/Pattern/CircuitBreaker.cs (hunk 2 above)
Comment (Aaronontheweb) [reply src/core/Akka/Pattern/CircuitBreaker.cs]: > I guess another way of doing this by making `OnFail` and `OnSuccess` callback and store/clear the last caught exception in the circuit breaker class instead, do you think that'll be cleaner?

Yes, I think that's a cleaner way of doing this. Let's do that.

**Comment by Aaronontheweb** [comment]
Thanks @Arkatufus - I'll review this ASAP

File: src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt [hunk 4]
```diff
@@ -3891,10 +3891,11 @@ namespace Akka.Pattern
         public bool IsClosed { get; }
         public bool IsHalfOpen { get; }
         public bool IsOpen { get; }
+        public System.Exception LastCaughtException { get; }
         public int MaxFailures { get; }
         public System.TimeSpan ResetTimeout { get; }
         public static Akka.Pattern.CircuitBreaker Create(int maxFailures, System.TimeSpan callTimeout, System.TimeSpan resetTimeout) { }
-        public void Fail() { }
+        public void Fail(System.Exception cause = null) { }
```
[the remark this answers is not in the document]
Comment (Arkatufus) [reply src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt:3898]: OK, I'll figure out another way
