### PR TITLE
Fixes FailChunkExecution does not handle `DbExceptions` wrapped in an `AggregateException`

### LINKED ISSUE #6362: BatchingSqlJournal's FailChunkExecution mishandles `DbExceptions` wrapped in an `AggregateException`
**Version Information**
1.4.48
Akka.Persistence.Sql.Common

**Describe the bug**
Whenever a `DbException` is wrapped in an `AggregateException` (because of line [#1003](https://github.com/Arkatufus/akka.net/blob/4ad16ccfb4f044d164bd13bff2ba99e19abd3b29/src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs#L1003)), the `FailChunkException` method will mistreat it as a "non-database related" failure, thus failing to stop the persistent actor and leaving it in an unstable state.

**Expected behavior**
Unwrap `AggregateException`s to inspect the actual cause of the exception.

**Actual behavior**
Mishandles `AggregateException`s altogether.

### PR DESCRIPTION
**Pull request by ismaelhamed**
Fixes #6362

* [X] I have [reviewed my own pull request](https://getakka.net/community/contributing/index.html#review-your-own-pull-requests).

### CODE REVIEW

File: src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs [hunk 1]
```diff
@@ -762,7 +762,12 @@ protected sealed override bool Receive(object message)
         private void FailChunkExecution(ChunkExecutionFailure message)
         {
             _remainingOperations++;
-            var cause = message.Cause;
+
+            var cause = message.Cause is AggregateException aggregateException
+                ? aggregateException.Flatten().InnerExceptions.OfType<DbException>().FirstOrDefault()
+                    ?? aggregateException.Flatten().InnerExceptions[0]
+                : message.Cause;
+
```
Comment (ismaelhamed) [inline src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs:770]: An alternative to this would be to stop throwing an `AggregateException` in line [#1003](https://github.com/Arkatufus/akka.net/blob/4ad16ccfb4f044d164bd13bff2ba99e19abd3b29/src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs#L1003)

**Review by Aaronontheweb — APPROVED** [review]
LGTM

**Comment by Aaronontheweb** [comment]
@ismaelhamed do we need to backport this to v1.4?

**Comment by ismaelhamed** [comment]
Yes. We have a customer that is being impacted by this.

**Comment by Aaronontheweb** [comment]
@ismaelhamed we can do a deploy today if that'd help you

**Comment by ismaelhamed** [comment]
That'd be great @Aaronontheweb

**Comment by Aaronontheweb** [comment]
If you can send the PR, I'll prepare the release notes and take care of that today.
