### PR TITLE
fix NullReferenceException when logging UnhandledMessage from ActorRefs.NoSender

### LINKED ISSUE #3267: UnhandledMessageForwarder crashes and restarted every time the app is starting
```
...
[DEBUG][01/12/2018 07:45:23][Thread 0007][akka://host-states-system/user/app-restarter] Started (Akkling.Actors+FunActor`1[System.Object])
[ERROR][01/12/2018 07:45:23][Thread 0009][akka://host-states-system/system/UnhandledMessageForwarder] Object reference not set to an instance of an object.
Cause: System.NullReferenceException: Object reference not set to an instance of an object.
   at Akka.Event.LoggingBus.UnhandledMessageForwarder.ToDebug(UnhandledMessage message)
   at Akka.Event.LoggingBus.UnhandledMessageForwarder.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[DEBUG][01/12/2018 07:45:23][Thread 0007][akka://host-states-system/system/UnhandledMessageForwarder] Restarting
[DEBUG][01/12/2018 07:45:23][Thread 0007][akka://host-states-system/system/UnhandledMessageForwarder] Restarted (Akka.Event.LoggingBus+UnhandledMessageForwarder)
```

### PR DESCRIPTION
**Pull request by Aaronontheweb**
close #3267

Added reproduction spec to verify

### CODE REVIEW

File: src/core/Akka/Event/LoggingBus.cs [hunk 1]
```diff
@@ -257,9 +256,12 @@ protected override bool Receive(object message)
 
             private static Debug ToDebug(UnhandledMessage message)
             {
+                // avoid NREs when we have ActorRefs.NoSender
+                var sender = Equals(message.Sender, ActorRefs.NoSender) ? "NoSender" : message.Sender.Path.ToString();
```
Comment (Danthar) [inline src/core/Akka/Event/LoggingBus.cs]: Good alternative.

Comment (Aaronontheweb) [reply src/core/Akka/Event/LoggingBus.cs]: We did something similar for `DeadLetter` logging - figured repurposing that was the way to go
