### PR TITLE
Akka.DistributedData: fix ORMultiDictionary Delta Serialization

### LINKED ISSUE #4367: ORMultiValueDictionary - DistributedData Serialization InvalidCastException Unable to cast object of type 'DeltaGroup[System.String]' to type 'Akka.DistributedData.ORSet1[System.String]'
- Which Akka.Net version you are using
1.4.4

- On which platform you are using Akka.Net
net 4.7

We are using Distributed registry and have a ORMultiValueDictionary collection. And often we see the below error logged in the akka logs. 

[System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'DeltaGroup[System.String]' to type 'Akka.DistributedData.ORSet1[System.String]'. at Akka.DistributedData.Serialization.ReplicatedDataSerializer.<>c__DisplayClass95_02.<GenericORDictionaryDeltaGroupFromProto>gMapEntryFromProto|0(MapEntry entry)
at System.Linq.Enumerable.<>cDisplayClass7_03.<CombineSelectors>b__0(TSource x) at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
at System.Collections.Immutable.ImmutableDictionary2.AddRange(IEnumerable1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
at System.Collections.Immutable.ImmutableDictionary2.AddRange(IEnumerable1 pairs, Boolean avoidToHashMap)
at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionaryTSource,TKey,TValue
at Akka.DistributedData.Serialization.ReplicatedDataSerializer.GenericORDictionaryDeltaGroupFromProtoTKey,TValue
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Akka.DistributedData.Serialization.ReplicatedDataSerializer.ORDictionaryDeltaGroupFromProto(ORMapDeltaGroup deltaGroup)
at Akka.DistributedData.Serialization.ReplicatedDataSerializer.ORMultiDictionaryDeltaFromBinary(Byte[] bytes)
at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
at Akka.DistributedData.Serialization.ReplicatorMessageSerializer.DataEnvelopeFromProto(DataEnvelope proto)
at Akka.DistributedData.Serialization.ReplicatorMessageSerializer.DeltaPropagationFromBinary(Byte[] bytes)
at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
at Akka.Remote.Serialization.MessageContainerSerializer.FromBinary(Byte[] bytes, Type type)
at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, Payload message, IActorRef senderOption)
at Akka.Remote.EndpointReader.<Reading>b__11_0(InboundPayload inbound)
at lambda_method(Closure , Object , Action1 , Action1 , Action1 ) at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture4.Handle(T value)
at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
at Akka.Actor.UntypedActor.Receive(Object message)
at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
at Akka.Actor.ActorCell.ReceiveMessage(Object message)
at Akka.Actor.ActorCell.Invoke(Envelope envelope)

### PR DESCRIPTION
**Pull request by Aaronontheweb**
close #4380 
close #4367

### CODE REVIEW

File: src/contrib/cluster/Akka.DistributedData/Serialization/ReplicatedDataSerializer.cs [hunk 1]
```diff
@@ -992,7 +992,10 @@ private ORDictionary.IDeltaGroupOp ORDictionaryDeltaGroupFromProto(Proto.Msg.ORM
 
                 if (entry.Value != null)
                 {
-                    return (k, (TValue)_ser.OtherMessageFromProto(entry.Value));
+                    // Bug #4367 throws here, value is ORDictionary.DeltaValue,
+                    // which can't be cast to ORSet
+                    var value = _ser.OtherMessageFromProto(entry.Value);
```
Comment (Aaronontheweb) [inline src/contrib/cluster/Akka.DistributedData/Serialization/ReplicatedDataSerializer.cs:995]: The bug turned out to be simpler than I thought - just a casting problem with how we handle `ORDictionary.DeltaGroup`s. I moved the casting out of this method and instead dealt with it at the point where we reconstitute the `DeltaGroup`. Looks like this turned all of the tests green,

**Comment by Aaronontheweb** [comment]
Had a feeling this might be an issue - we're not propagating the `WithValueDeltas` stuff correctly. Going to have to take another pass at that.

File: src/contrib/cluster/Akka.DistributedData/ORMultiValueDictionary.cs [hunk 2]
```diff
@@ -325,13 +329,13 @@ public IReplicatedData Merge(IReplicatedData other)
...
-                    return new ORMultiValueDictionaryDelta((ORDictionary<TKey, ORSet<TValue>>.IDeltaOperation)Underlying.Merge(d.Underlying));
+                    return new ORMultiValueDictionaryDelta((ORDictionary<TKey, ORSet<TValue>>.IDeltaOperation)Underlying.Merge(d.Underlying), WithValueDeltas || d.WithValueDeltas);
                 }
 
-                return new ORMultiValueDictionaryDelta((ORDictionary<TKey, ORSet<TValue>>.IDeltaOperation)Underlying.Merge(other));
+                return new ORMultiValueDictionaryDelta((ORDictionary<TKey, ORSet<TValue>>.IDeltaOperation)Underlying.Merge(other), WithValueDeltas);
             }
 
-            public IDeltaReplicatedData Zero => ORMultiValueDictionary<TKey, TValue>.Empty;
+            public IDeltaReplicatedData Zero => WithValueDeltas ? ORMultiValueDictionary<TKey, TValue>.EmptyWithValueDeltas : ORMultiValueDictionary<TKey, TValue>.Empty;
```
Comment (Aaronontheweb) [inline src/contrib/cluster/Akka.DistributedData/ORMultiValueDictionary.cs:338]: Needed this in order to make `DataEnvelope` merging work correctly for `ORMultiValueDictionary` to work correctly inside the `Replicator`

File: src/contrib/cluster/Akka.DistributedData/Serialization/ReplicatedDataSerializer.cs [hunk 3]
```diff
@@ -89,7 +89,7 @@ public override byte[] ToBinary(object obj)
                 case IPNCounterDictionary pn: return SerializationSupport.Compress(ToProto(pn));
                 case IPNCounterDictionaryDeltaOperation pnd: return ToProto(pnd.Underlying).ToByteArray();
                 case IORMultiValueDictionary m: return SerializationSupport.Compress(ToProto(m));
-                case IORMultiValueDictionaryDeltaOperation md: return ToProto(md.Underlying).ToByteArray();
+                case IORMultiValueDictionaryDeltaOperation md: return ToProto(md).ToByteArray();
```
Comment (Aaronontheweb) [inline src/contrib/cluster/Akka.DistributedData/Serialization/ReplicatedDataSerializer.cs:92]: Fixed the serialization of `IORMultiValueDictionaryDeltaOperation`s by having them explicitly include the `WithValueDelta` setting that will be passed into the underlying collection.

File: src/protobuf/ReplicatedDataMessages.proto [hunk 4]
```diff
@@ -119,6 +119,11 @@ message ORMapDeltaGroup {
   TypeDescriptor valueTypeInfo = 3;
 }
 
+message ORMultiMapDelta {
```
Comment (Aaronontheweb) [inline src/protobuf/ReplicatedDataMessages.proto:122]: Added a new protobuf message type to carry this payload over the wire.
