### PR TITLE
Fixes initialization of LocalSnapshotStore directory

### LINKED ISSUE #1751: Racy Spec: SnapshotDirectoryFailureSpec.LocalSnapshotStore_configured_with_a_failing_directory_name_should_throw_an_exception_at_startup
```
System.IO.DirectoryNotFoundException : Could not find a part of the path 'D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Persistence.Tests\bin\Release\target\inUseSnapshotPath'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.FileInfo.Create()
   at Akka.Persistence.Tests.SnapshotDirectoryFailureSpec.AtStartup() in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Persistence.Tests\SnapshotDirectoryFailureSpec.cs:line 61
   at Akka.TestKit.AkkaSpec..ctor(Config config, ITestOutputHelper output) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Tests.Shared.Internals\AkkaSpec.cs:line 52
   at Akka.Persistence.Tests.PersistenceSpec..ctor(Config config, ITestOutputHelper output) in D:\BuildAgent\work\d26c9d7f36545acd\src\core\Akka.Persistence.Tests\PersistenceSpec.cs:line 56
```

Relatively new failure - might be related to some of the changes we've made to Akka.Persistence cc @cconstantin @Horusiath

### PR DESCRIPTION
**Pull request by cconstantin**
Closes #1751

### CODE REVIEW

File: src/core/Akka.Persistence/Snapshot/LocalSnapshotStore.cs [hunk 1]
```diff
@@ -244,12 +244,35 @@ private SnapshotMetadata ExtractSnapshotMetadata(FileInfo fileInfo)
...
+                {
+                    dirCreated = false;
+                }
+                finally
+                {
+                    _dir.Refresh();
+                }
+                if (!dirCreated || ((_dir.Attributes & FileAttributes.Directory) == 0))
+                {
+                    throw new IOException("Failed to create snapshot directory " + _dir.FullName);
```
Comment (Horusiath) [inline src/core/Akka.Persistence/Snapshot/LocalSnapshotStore.cs]: Maybe we should keep cause of a problem as inner exception here?

**Comment by cconstantin** [comment]
@Horusiath updated based on your suggestion to include underlying exception as inner exception.
