### PR TITLE
Mark socket connection messages with IDeadLetterSuppression

### LINKED ISSUE #5318: UDP Connected: Unhandled message SocketReceived
**Version Information**
Version of Akka.NET? 1.4.25
Which Akka.NET Modules? Akka.IO

**Describe the bug**
When communication with the device is complete, we send a UdpConnected.Disconnect message to close the socket. 
After that, we receive UdpConnected.Disconnected but we see an unhandled message in UdpConnection actor: 

  Message [SocketReceived] to [akka://dlmshe/system/IO-UDP-CONN/$a#267206278] was not delivered. [1] dead letters 
  encountered. If this is not an expected behavior then [akka://dlmshe/system/IO-UDP-CONN/$a#267206278] may have 
  terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 
  'akka.log-dead-letters-during-shutdown'.

**Expected behavior**
UDP socket is closed successfully. 

**Actual behavior**
UDP socket is closed successfully but we see an unhandled message. 

**Environment**
Windows
.NET Framework 4.8

DeadLetter
[akka_seq_logs.csv](https://github.com/akkadotnet/akka.net/files/7345357/akka_seq_logs.csv)

### PR DESCRIPTION
**Pull request by Arkatufus**
Closes #5318
Socket connection messages like SocketReceived can arrive late to a dead socket listener after the socket actor is closed.
The log message from the deadletter actor made it look like it is a bigger problem than it is, when we know that this is a benign behaviour.
Marking these messages as IDeadLetterSuppression so it will not confuse user when it happens.

### CODE REVIEW

File: src/core/Akka/IO/Tcp.cs [hunk 1]
```diff
@@ -53,7 +50,8 @@ public override TcpExt CreateExtension(ExtendedActorSystem system)
 
         #region internal connection messages
         
-        internal abstract class SocketCompleted : INoSerializationVerificationNeeded { }
+        internal abstract class SocketCompleted : INoSerializationVerificationNeeded, IDeadLetterSuppression
```
Comment (Aaronontheweb) [inline src/core/Akka/IO/Tcp.cs:53]: LGTM

**Review by Aaronontheweb — APPROVED** [review]
LGTM - no need for API approval as these are all `internal` classes.

**Comment by Aaronontheweb** [comment]
Clearing milestone since the issue this resolves is part of it.
