### PR TITLE
fix logging issue with system actor race upon startup

### LINKED ISSUE #2829: Application hangs on shutdown when using remote provider (1.2.2)
As long as provider is set to Akka.Actor.LocalActorRefProvider all works fine, switched to Akka.Remote.RemoteActorRefProvider, Akka.Remote (tried both Helios and DotNetty), when I tried to stop the application services, the following lines appear in the log:

2017-07-05 16:36:35 [Debug] "received AutoReceiveMessage <Terminated>: [akka://OJ/user] - ExistenceConfirmed=True"
2017-07-05 16:36:35 [Information] "Shutting down remote daemon."
2017-07-05 16:36:35 [Error] "Object reference not set to an instance of an object."
System.NullReferenceException: Object reference not set to an instance of an object.
at Akka.Remote.RemoteSystemDaemon.<TerminationHookDoneWhenNoChildren>b__5_0()
2017-07-05 16:36:35 [Debug] "Restarting"
2017-07-05 16:36:35 [Debug] "Restarted (Akka.Remote.RemoteActorRefProvider+RemotingTerminator)"

The issue may have been already addressed here: https://github.com/akkadotnet/akka.net/pull/2817

### PR DESCRIPTION
**Pull request by Aaronontheweb**
close #2829

### CODE REVIEW

File: src/core/Akka/Event/Logging.cs [hunk 1]
```diff
@@ -91,7 +91,8 @@ public static ILoggingAdapter GetLogger(this IActorContext context, ILogMessageF
         {
             // if we're runing Akka.Remote or Akka.Cluster, this will grab the default inbound listening address
             // otherwise, it'll default to just using the local absolute path
-            var addr = ((ExtendedActorSystem) context.System).Provider.DefaultAddress ?? Address.AllSystems;
+            var provider = ((ExtendedActorSystem) context.System).Provider;
```
Comment (Aaronontheweb) [inline src/core/Akka/Event/Logging.cs]: yeah this ain't gonna fix it, based on your earlier comments @zbynek001 .... need to come up with some way to allow us to capture the self - address value if the actor being started is launched before the `RemoteActorRefProvider` finishes initializing...

**Comment by Aaronontheweb** [comment]
@zbynek001 @object I ended up rolling back #2368 - it's just too dangerous with all of the timings around when stuff starts to try to grab that `Provider.DefaultAddress` at the beginning.

I also changed the initialization code for the Akka.Remote `Internals` so it can't be initiated more than once.

File: src/core/Akka.Remote/RemoteActorRefProvider.cs [hunk 2]
```diff
@@ -177,6 +154,8 @@ public virtual void Init(ActorSystemImpl system)
                     RemoteSettings.ConfigureDispatcher(Props.Create(() => new RemotingTerminator(_local.SystemGuardian))),
                     "remoting-terminator");
 
+            _internals = CreateInternals();
```
Comment (Aaronontheweb) [inline src/core/Akka.Remote/RemoteActorRefProvider.cs]: We can only create the internals once now.

**Comment by Aaronontheweb** [comment]
Going to run this one a few times on CI and see if some of the race conditions we've observed in some of the remoting specs on Mono reappear, since they're directly related to this:

```
Akka.Actor.InvalidActorNameException : Actor name "transports" is not unique!
  at Akka.Actor.Internal.NormalChildrenContainer.Reserve (System.String name) [0x0001e] in <1f75f87f790d4c0c8c2662a684fa10cf>:0 
  at Akka.Actor.ActorCell+<>c__DisplayClass13_0.<ReserveChild>b__0 (Akka.Actor.Internal.IChildrenContainer c) [0x00000] in <1f75f87f790d4c0c8c2662a684fa10cf>:0 
  at Akka.Util.Internal.InterlockedSpin.Swap[T] (T& reference, System.Func`2[T,TResult] updater) [0x0000f] in <1f75f87f790d4c0c8c2662a684fa10cf>:0 
  at Akka.Actor.ActorCell.UpdateChildrenRefs (System.Func`2[T,TResult] updater) [0x00000] in <1f75f87f790d4c0c8c2662a684fa10cf>:0 
  at Akka.Actor.ActorCell.ReserveChild (System.String name) [0x0000d] in <1f75f87f790d4c0c8c2662a684fa10cf>:0 
  at Akka.Actor.ActorCell.MakeChild (Akka.Actor.Props props, System.String name, System.Boolean async, System.Boolean systemService) [0x0012b] in <1f75f87f790d4c0c8c2662a684fa10cf>:0 
  at Akka.Actor.ActorCell.AttachChild (Akka.Actor.Props props, System.Boolean isSystemService, System.String name) [0x00013] in <1f75f87f790d4c0c8c2662a684fa10cf>:0 
  at Akka.Actor.Internal.ActorSystemImpl.SystemActorOf (Akka.Actor.Props props, System.String name) [0x00010] in <1f75f87f790d4c0c8c2662a684fa10cf>:0 
  at Akka.Remote.Remoting..ctor (Akka.Actor.ExtendedActorSystem system, Akka.Remote.RemoteActorRefProvider provider) [0x00048] in <ef0a0a0a1efb4a65a6a14595f364760a>:0 
  at Akka.Remote.RemoteActorRefProvider.CreateInternals () [0x00000] in <ef0a0a0a1efb4a65a6a14595f364760a>:0 
  at Akka.Remote.RemoteActorRefProvider.get_RemoteInternals () [0x0000c] in <ef0a0a0a1efb4a65a6a14595f364760a>:0 
  at Akka.Remote.RemoteActorRefProvider.Init (Akka.Actor.Internal.ActorSystemImpl system) [0x00096] in <ef0a0a0a1efb4a65a6a14595f364760a>:0 
  at Akka.Actor.Internal.ActorSystemImpl.Start () [0x00097] in <1f75f87f790d4c0c8c2662a684fa10cf>:0 
  at Akka.Actor.ActorSystem.CreateAndStartSystem (System.String name, Akka.Configuration.Config withFallback) [0x00007] in <1f75f87f790d4c0c8c2662a684fa10cf>:0 
  at Akka.Actor.ActorSystem.Create (System.String name, Akka.Configuration.Config config) [0x00000] in <1f75f87f790d4c0c8c2662a684fa10cf>:0 
  at Akka.TestKit.TestKitBase.InitializeTest (Akka.Actor.ActorSystem system, Akka.Configuration.Config config, System.String actorSystemName, System.String testActorName) [0x00025] in <abe06d5c53ef4bbc819197e51d659509>:0 
  at Akka.TestKit.TestKitBase..ctor (Akka.TestKit.ITestKitAssertions assertions, Akka.Actor.ActorSystem system, Akka.Configuration.Config config, System.String actorSystemName, System.String testActorName) [0x00020] in <abe06d5c53ef4bbc819197e51d659509>:0 
  at Akka.TestKit.TestKitBase..ctor (Akka.TestKit.ITestKitAssertions assertions, Akka.Configuration.Config config, System.String actorSystemName, System.String testActorName) [0x0000d] in <abe06d5c53ef4bbc819197e51d659509>:0 
  at Akka.TestKit.Xunit2.TestKit..ctor (Akka.Configuration.Config config, System.String actorSystemName, Xunit.Abstractions.ITestOutputHelper output) [0x00006] in <c39c51a0c4ec47f4926c55cc502785d4>:0 
  at Akka.TestKit.AkkaSpec..ctor (Akka.Configuration.Config config, Xunit.Abstractions.ITestOutputHelper output) [0x00011] in <1502d1e9f0f242a093318b2253b9c0e1>:0 
  at Akka.Persistence.Tests.Serialization.MessageSerializerRemotingSpec.ExpectMsgAllOf[T] (System.TimeSpan max, T[] messages) [0x00029] in <48046069d20c4cd993d2a57c081a0306>:0 
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <a07d6bf484a54da2861691df910339b1>:0 
```

**Comment by Aaronontheweb** [comment]
(that error was from a different PR)

**Comment by Aaronontheweb** [comment]
Ran the full Mono test suite 4 times; no errors.
