### PR TITLE
Fix #1522 Ensure extensions and persistence plugins are only registered/created once

### LINKED ISSUE #1522: Multiple Persistence actors of same type, different names throw Actor name \"akka.persistence.journal.inmem\" is not unique!
My scenario involves an AtLeastOnce delivery actor that i am using as a client for 2 different services. 

So i have 2 instances of the same actor type but with 2 different names - they differ as the props passes in the address to use as a path.

In the actor prestart i set up a scheduler to snapshot every second - this causes a cant stash messages more than once error however on actor restart i then get this:
```
GetCandidatePromotion
2015-12-09 12:32:11 [Error] "Can't stash the same message PromotionPlanning.Akka.GuranteedDelivererClientProxy+SnapshotMessages more than once"
Akka.Actor.IllegalActorStateException: Can't stash the same message PromotionPlanning.Akka.GuranteedDelivererClientProxy+SnapshotMessages more than once
   at Akka.Actor.Internal.AbstractStash.Stash()
   at Akka.Persistence.Eventsourced.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
2015-12-09 12:32:11 [Error] "Can't stash the same message PromotionPlanning.Akka.GuranteedDelivererClientProxy+SnapshotMessages more than once"
Akka.Actor.IllegalActorStateException: Can't stash the same message PromotionPlanning.Akka.GuranteedDelivererClientProxy+SnapshotMessages more than once
   at Akka.Actor.Internal.AbstractStash.Stash()
   at Akka.Persistence.Eventsourced.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
2015-12-09 12:32:11 [Debug] "Restarting"
2015-12-09 12:32:11 [Debug] "Restarting"
2015-12-09 12:32:11 [Debug] "now supervising akka://clientActorSystem/system/akka.persistence.journal.inmem"
2015-12-09 12:32:11 [Error] "Actor name \"akka.persistence.journal.inmem\" is not unique!"
Akka.Actor.PreRestartException: Exception of type 'Akka.Actor.PreRestartException' was thrown.
2015-12-09 12:32:11 [Error] "Object reference not set to an instance of an object."
[akka://clientActorSystem/system/akka.persistence.journal.inmem]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass110_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SystemInvoke(Envelope envelope)
2015-12-09 12:32:11 [Debug] "Restarted (PromotionPlanning.Akka.GuranteedDelivererClientProxy)"
```

tis spirals into a loop until the timeout on my expect is hit.

The workaround suggested in gitter which works is to call this immediatley after system creation
`Persistence.Instance.Apply(_clientTestkit.Sys).JournalFor(null);`

with this workaround i get a stash same message wtice error and then everythign continues as expected (well a message is not getting received on the server side but i suspect that is a bug in my code)

### PR DESCRIPTION
**Pull request by cconstantin**
Use ConcurrentDictionary.GetOrAdd instead of TryGet + AddOrUpdate

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@Horusiath @zetanova care to comment on this, Akka.Persistence gurus?

**Comment by Zetanova** [comment]
The combination of AtomicReference TrySet+CompareAndSet(of IImmutableMap)+Get  should be thread safe. If there is a race condition then it is likly to be in likly ImmutableTreeMap or unlikly in AtomicReferenece 

Maybe fix for ImmutableTreeMap:
https://github.com/akkadotnet/akka.net/pull/1645

Maybe Fix for AttomicReference:
https://github.com/akkadotnet/akka.net/pull/1615

**Comment by cconstantin** [comment]
I have a test that's calling SnapshotFor in two threads concurrently. Fails on `dev`, passes with the fix. I'll find an appropriate location for it and push it up.





On Fri, Jan 15, 2016 at 7:58 PM -0800, "Zetanova" <notifications@github.com> wrote:












The combination of AtomicReference TrySet+CompareAndSet(of IImmutableMap)+Get  should be thread safe. If there is a race condition then it is likly to be in likly ImmutableTreeMap or unlikly in AtomicReferenece 



Maybe fix for ImmutableTreeMap:

#1645



Maybe Fix for AttomicReference:

#1615

File: src/core/Akka/Actor/Internal/ActorSystemImpl.cs [hunk 1]
```diff
@@ -177,10 +177,8 @@ private void ConfigureExtensions(IEnumerable<IExtensionId> extensionIdProviders)
         public override object RegisterExtension(IExtensionId extension)
         {
             if(extension == null) return null;
-            if(!_extensions.ContainsKey(extension.ExtensionType))
-            {
-                _extensions.TryAdd(extension.ExtensionType, new Lazy<object>(() => extension.CreateExtension(this)));
-            }
```
Comment (rogeralsing) [inline src/core/Akka/Actor/Internal/ActorSystemImpl.cs]: This part was the cause for race conditions in the old code.
there is a check if something does not exist, and if so, it adds an extension.. classic race condition semantics.

The new code fixes that.

File: src/core/Akka.Persistence/Persistence.cs [hunk 2]
```diff
@@ -81,15 +79,13 @@ public string PersistenceId(IActorRef actor)
...
         {
             var configPath = string.IsNullOrEmpty(snapshotPluginId) ? _defaultSnapshotPluginId.Value : snapshotPluginId;
-            Lazy<PluginHolder> pluginContainer;
-            var extensionIdMap = _snapshotPluginExtensionIds.Value;
-            if (!extensionIdMap.TryGet(configPath, out pluginContainer))
-            {
-                pluginContainer = new Lazy<PluginHolder>(() => CreatePlugin(configPath, _ => DefaultPluginDispatcherId), LazyThreadSafetyMode.ExecutionAndPublication);
-                _snapshotPluginExtensionIds.CompareAndSet(extensionIdMap, extensionIdMap.AddOrUpdate(configPath, pluginContainer));
-                return SnapshotStoreFor(snapshotPluginId);
-            }
```
Comment (rogeralsing) [inline src/core/Akka.Persistence/Persistence.cs]: This part was the cause for race conditions in the old code.
there is a check if something does not exist, and if so, it adds an extension.. classic race condition semantics.

The new code fixes that.

File: src/core/Akka.Persistence/Persistence.cs [hunk 3]
```diff
@@ -99,19 +95,17 @@ public IActorRef SnapshotStoreFor(string snapshotPluginId)
         public IActorRef JournalFor(string journalPluginId)
         {
             var configPath = string.IsNullOrEmpty(journalPluginId) ? _defaultJournalPluginId.Value : journalPluginId;
-            Lazy<PluginHolder> pluginContainer;
-            var extensionIdMap = _journalPluginExtensionIds.Value;
-            if (!extensionIdMap.TryGet(configPath, out pluginContainer))
-            {
-                pluginContainer = new Lazy<PluginHolder>(() => CreatePlugin(configPath, type =>
-                    typeof (AsyncWriteJournal).IsAssignableFrom(type)
```
Comment (rogeralsing) [inline src/core/Akka.Persistence/Persistence.cs]: This part was the cause for race conditions in the old code.
there is a check if something does not exist, and if so, it adds an extension.. classic race condition semantics.

The new code fixes that.

File: src/core/Akka.Persistence/Persistence.cs [hunk 4]
```diff
@@ -124,18 +118,17 @@ public IActorRef JournalFor(string journalPluginId)
         public EventAdapters AdaptersFor(string journalPluginId)
         {
             var configPath = string.IsNullOrEmpty(journalPluginId) ? _defaultJournalPluginId.Value : journalPluginId;
-            Lazy<PluginHolder> pluginContainer;
-            var extensionIdMap = _journalPluginExtensionIds.Value;
-            if (!extensionIdMap.TryGet(configPath, out pluginContainer))
-            {
-                pluginContainer = new Lazy<PluginHolder>(() =>
-                    CreatePlugin(configPath, type => typeof (AsyncWriteJournal).IsAssignableFrom(type)
```
Comment (rogeralsing) [inline src/core/Akka.Persistence/Persistence.cs]: This part was the cause for race conditions in the old code.
there is a check if something does not exist, and if so, it adds an extension.. classic race condition semantics.

The new code fixes that.

**Comment by rogeralsing** [comment]
The problems in the old code does not relate to atomic references or immutable lists, it comes down to standard race conditions... 

```
IF something THEN  //this 
    DOSTUFF              //is racy...
```

File: src/core/Akka.Persistence/Persistence.cs (hunk 2 above)
Comment (Zetanova) [inline src/core/Akka.Persistence/Persistence.cs]: It should be thread safe. CompareAndSet Sets only the new value if extensionIdMap is still the same. SnapshotStoreFor should return allways the valid value

File: src/core/Akka.Persistence/Persistence.cs (hunk 3 above)
Comment (Zetanova) [inline src/core/Akka.Persistence/Persistence.cs]: It should be thread safe. CompareAndSet Sets only the new value if extensionIdMap is still the same. JournalFo rshould return allways the valid value

File: src/core/Akka/Actor/Internal/ActorSystemImpl.cs (hunk 1 above)
Comment (Zetanova) [inline src/core/Akka/Actor/Internal/ActorSystemImpl.cs]: this can be the couse. Should that "return extension.Get(this);" not actualy using the result of _extensions.GetOrAdd ?

Comment (rogeralsing) [inline src/core/Akka/Actor/Internal/ActorSystemImpl.cs]: yes, it could just do a return on that call.

**Comment by Aaronontheweb** [comment]
I reviewed this also and agreed with @rogeralsing - better to use a `ConcurrentDictionary` here.

**Comment by Aaronontheweb** [comment]
Just for reference, in @Horusiath's original PR he talked about some of the potential trade-offs of switching to `ConcurrentDictionary`. Putting this here just in case merging this code comes back to bite us in the ass :p 

https://github.com/akkadotnet/akka.net/pull/1543
