### PR TITLE
use `Failure` to programmatically cancel `Ask`

### LINKED ISSUE #3019: Persistence plugins need to support SerializerWithStringManifest
Right now it seems that the Sqlite and the SqlServer plugins does not support `SerializerWithStringManifest`. 

See: https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/persistence/Akka.Persistence.Sqlite.Tests/Serialization/SqliteJournalSerializationSpec.cs#L51 For Sqlite.

The current SqlServer plugin is being updated to 1.3. See: https://github.com/akkadotnet/Akka.Persistence.SqlServer/pull/73
However that PR still does not support `SerializerWithStringManifest`. 

Support for `SerializerWithStringManifest` is important. Because cluster sharding demands it. So right now using cluster sharding in combination with the Sql plugins will cause problems.

### LINKED ISSUE #3091: Ask does not set exception on the underlying TaskCompletionSource when callee responds with Failure
Hello,

I am running Akka.net 1.3.0 on .NET Core, and came across the following issue:

I am calling `Ask<TResult>` from outside of the system and would like to have Ask throw an exception at the call site if the underlying actor responds with `new Failure() { Exception = ex }` instead of `TResult`.

This behaviour is described in the docs:

> To complete the Task with an exception you need send a Failure message to the sender. This is not done automatically when an actor throws an exception while processing a message.

- http://getakka.net/articles/actors/receive-actor-api.html#ask-send-and-receive-future
- http://getakka.net/articles/actors/untyped-actor-api.html#ask-send-and-receive-future

This feature is however not implemented, if you look at https://github.com/akkadotnet/akka.net/blob/a478c5e8c8d5de97dcf7bcea7e2a80fbaa5e6cc8/src/core/Akka/Actor/ActorRef.cs#L129 the `FutureActorRef` sets the result of the task without inspecting whether the message is a `Failure`.

This then breaks `Ask<TResult>` as the underlying extension method tries to cast `Failure` to `TResult`.

Unless I am mistaken the following modification could be used:
```
if (message is Failure failure) {
    _result.TrySetException(failure.Exception ?? new SomeDefaultException())
} else {
    _result.TrySetResult(message);
}
```

I am assuming this is still a behaviour you want to support. If not then the docs should be updated so that they don't put peoples hopes up :)

Many thanks,
Ondrej.

### PR DESCRIPTION
**Pull request by Aaronontheweb**
close #3091 - part of the `Ask` API that's never been fully implemented.

### CODE REVIEW

File: src/core/Akka/Actor/ActorRef.cs [hunk 1]
```diff
@@ -142,15 +146,6 @@ protected override void TellInternal(object message, IActorRef sender)
                 }
             }
         }
-
-        /// <summary>
-        /// TBD
-        /// </summary>
-        /// <param name="message">TBD</param>
-        public override void SendSystemMessage(ISystemMessage message)
```
Comment (Aaronontheweb) [inline src/core/Akka/Actor/ActorRef.cs:150]: Bah, getting rid of this is a "public API change"

Comment (Aaronontheweb) [reply src/core/Akka/Actor/ActorRef.cs]: Reverted that

**Review by Arkatufus — APPROVED** [review]
LGTM
