### PR TITLE
Fix DData infinite status/gossip round

### LINKED ISSUE #5022: Akka.DistributedData: memory leak when recovering events from LMDB data store
Version: Akka.NET v1.4.19

Reproduction: https://github.com/andyfurnival/ddata 

Memory consumption grows steadily in a 2 node cluster, with both nodes recovering events from their own LMDB data stores:

image

The drivers of memory consumption appear to be non-stop gossip between the replicators:

image

I think there must be an equality check that is failing somewhere in this system, causing the same objects to be gossiped over and over again. We're not even producing any new events other than what's been deserialized from LMDB in this sample and yet the memory grows continuously.

### PR DESCRIPTION
**Pull request by Arkatufus**
Closes #5022

### CODE REVIEW

File: src/contrib/cluster/Akka.DistributedData.LightningDB/LmdbDurableStore.cs [hunk 1]
```diff
@@ -80,11 +82,16 @@ public LmdbDurableStore(Config config)
...
+            _mapSize = _config.GetByteSize("map-size") ?? 100 * 1024 * 1024;
+
             var path = _config.GetString("dir");
             _dir = path.EndsWith(DatabaseName)
                 ? Path.GetFullPath($"{path}-{Context.System.Name}-{Self.Path.Parent.Name}-{Cluster.Cluster.Get(Context.System).SelfAddress.Port}")
                 : Path.GetFullPath(path);
 
+            _dirExists = Directory.Exists(_dir);
+
+            _log.Info($"Using durable data in LMDB directory [{_dir}]");
```
Comment (Arkatufus) [inline src/contrib/cluster/Akka.DistributedData.LightningDB/LmdbDurableStore.cs:94]: Move logging here, should be called once at startup, not every time a new LMDB environment is created

File: src/contrib/cluster/Akka.DistributedData/Serialization/Proto/OtherMessage.cs [hunk 2]
```diff
@@ -0,0 +1,32 @@
+﻿using System;
+using System.Collections.Generic;
+using System.Text;
+
+namespace Akka.DistributedData.Serialization.Proto.Msg
+{
+    internal sealed partial class OtherMessage : IComparable<OtherMessage>
```
Comment (Arkatufus) [inline src/contrib/cluster/Akka.DistributedData/Serialization/Proto/OtherMessage.cs:7]: Needed to allow `OtherMessage` can be sorted

File: src/contrib/cluster/Akka.DistributedData/Serialization/ReplicatedDataSerializer.cs [hunk 3]
```diff
@@ -251,57 +251,77 @@ private static Type GetTypeFromDescriptor(TypeDescriptor t)
...
                 case ORSet<int> ints:
                     {
-                        var p = ORSetToProto(ints);
-                        p.TypeInfo.Type = ValType.Int;
-                        p.IntElements.Add(ints.Elements);
-                        return p;
+                        b.Vvector =  SerializationSupport.VersionVectorToProto(ints.VersionVector);
+                        b.TypeInfo.Type = ValType.Int;
+                        var intElements = new List<int>(ints.ElementsMap.Keys);
+                        intElements.Sort();
```
Comment (Arkatufus) [inline src/contrib/cluster/Akka.DistributedData/Serialization/ReplicatedDataSerializer.cs:273]: ORSet elements need to be sorted during serialization so that it have consistent SHA-1 digest

File: src/contrib/cluster/Akka.DistributedData/Serialization/ReplicatedDataSerializer.cs [hunk 4]
```diff
@@ -251,57 +251,77 @@ private static Type GetTypeFromDescriptor(TypeDescriptor t)
...
+                        foreach (var val in intElements)
+                        {
+                            b.IntElements.Add(val);
+                            b.Dots.Add(SerializationSupport.VersionVectorToProto(ints.ElementsMap[val]));
```
Comment (Arkatufus) [inline src/contrib/cluster/Akka.DistributedData/Serialization/ReplicatedDataSerializer.cs:277]: ElementsMap isn't serialized as a dictionary, instead keys and version vector are serialized as separate lists. Due to this serialization scheme, key ordering and value ordering matters. VersionVector need to be inserted in the same order as the newly sorted keys.

File: src/contrib/cluster/Akka.DistributedData.LightningDB/LmdbDurableStore.cs [hunk 5]
```diff
@@ -80,11 +82,16 @@ public LmdbDurableStore(Config config)
                     TimeSpan.Zero :
                     _config.GetTimeSpan("write-behind-interval");
 
+            _mapSize = _config.GetByteSize("map-size") ?? 100 * 1024 * 1024;
```
Comment (Aaronontheweb) [inline src/contrib/cluster/Akka.DistributedData.LightningDB/LmdbDurableStore.cs:85]: This was always the default size, so no big deal.

File: src/contrib/cluster/Akka.DistributedData.LightningDB/LmdbDurableStore.cs [hunk 6]
```diff
@@ -53,9 +53,11 @@ private sealed class WriteBehind : IDeadLetterSuppression
         private readonly Akka.Serialization.Serialization _serialization;
         private readonly SerializerWithStringManifest _serializer;
         private readonly string _manifest;
+        private readonly long _mapSize;
 
         private readonly TimeSpan _writeBehindInterval;
         private readonly string _dir;
+        private bool _dirExists;
```
Comment (Aaronontheweb) [inline src/contrib/cluster/Akka.DistributedData.LightningDB/LmdbDurableStore.cs:60]: Good idea to cache this

File: src/contrib/cluster/Akka.DistributedData/Serialization/Proto/OtherMessage.cs (hunk 2 above)
Comment (Aaronontheweb) [reply src/contrib/cluster/Akka.DistributedData/Serialization/Proto/OtherMessage.cs:7]: Would it be easier to just write an [`IComparer`](https://docs.microsoft.com/en-us/troubleshoot/dotnet/csharp/use-icomparable-icomparer)? So we don't have to hack around a generated class?

**Review by Aaronontheweb — CHANGES_REQUESTED** [review]
One small change

File: src/contrib/cluster/Akka.DistributedData/Serialization/OtherMessageComparer.cs [hunk 7]
```diff
@@ -0,0 +1,34 @@
+﻿using System;
+using System.Collections.Generic;
+using System.Text;
+using Akka.DistributedData.Serialization.Proto.Msg;
+
+namespace Akka.DistributedData.Serialization
+{
+    internal class OtherMessageComparer : IComparer<OtherMessage>
```
Comment (Aaronontheweb) [inline src/contrib/cluster/Akka.DistributedData/Serialization/OtherMessageComparer.cs:8]: We should make this `static` and have a `readonly` singleton here, but we can easily do that in an update

**Review by Aaronontheweb — APPROVED** [review]
LGTM

File: src/contrib/cluster/Akka.DistributedData/Serialization/OtherMessageComparer.cs (hunk 7 above)
Comment (Aaronontheweb) [reply src/contrib/cluster/Akka.DistributedData/Serialization/OtherMessageComparer.cs:8]: Ah, you already did that inside the serializer
