### PR TITLE
Fix TestKitBase and Option<T>

### LINKED ISSUE #4496: Multiple tests run fails with Akka.TestKit 1.4.8 (worked fine with 1.4.7)
Hi,

Akka: 1.4.8, NUnit3 package, Windows 10 Pro, .NET Framework 4.7.2, using Resharper to run tests.

Just upgraded from 1.4.7 to 1.4.8 and noticed that tests are failing with:
```
System.NullReferenceException : Object reference not set to an instance of an object.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
   at Akka.TestKit.TestKitBase.<>c.<InitializeTest>b__10_1(Config c)
   at Akka.Util.Option`1.Select[TNew](Func`2 selector)
   at Akka.TestKit.TestKitBase.InitializeTest(ActorSystem system, ActorSystemSetup config, String actorSystemName, String testActorName)
   at Akka.TestKit.NUnit3.TestKit.InitializeActorSystemOnSetUp()
--TearDown
   at Akka.TestKit.TestKitBase.Dilated(TimeSpan duration)
   at Akka.TestKit.TestKitBase.Shutdown(ActorSystem system, Nullable`1 duration, Boolean verifySystemShutdown)
   at Akka.TestKit.TestKitBase.Shutdown(Nullable`1 duration, Boolean verifySystemShutdown)
   at Akka.TestKit.NUnit3.TestKit.AfterAll()
```
tests pass if I run one at a time, but run fails with several tests selected within such run.

If Akka.TestKit is rolled back to 1.4.7 then everything's back to normal.

Thank you!

### PR DESCRIPTION
**Pull request by Arkatufus**
Closes #4496.

Original problem was that 
- `Option<T>` failed to report that it has no value when passed a null value.
- `TestKitBase` did not check for `Option<Config>.None`

### CODE REVIEW

File: src/core/Akka/Util/Option.cs [hunk 1]
```diff
@@ -30,7 +30,7 @@ public struct Option<T>
         public Option(T value)
         {
             Value = value;
-            HasValue = true;
+            HasValue = value != null;
```
Comment (IgorFedchenko) [inline src/core/Akka/Util/Option.cs:33]: I was always thinking about that - but what if `null` in a valid value for this optional thing? What if `null` means "there is a value, it is obtained from external source/whatever, it is initialized, and it is `null` right now"?

Comment (Arkatufus) [reply src/core/Akka/Util/Option.cs:33]: No, by definition Option<T> will return None or Some, what is the point of using Option if you still allow null to leak through? you wouldn't fix the original NRE problem.

Comment (Arkatufus) [reply src/core/Akka/Util/Option.cs:33]: Even with this, you'll still have NRE problem if you forgot to check for None.

Comment (Arkatufus) [reply src/core/Akka/Util/Option.cs:33]: In essence, Option is a half assed attempt to fix NRE problem, its just moving the problem somewhere else.

Comment (Arkatufus) [reply src/core/Akka/Util/Option.cs:33]: If you still need a null, then what you need is a tri-state object, where its state can be null, none, and some

Comment (IgorFedchenko) [reply src/core/Akka/Util/Option.cs:33]: And this will mean that `new Option(default(int)).HasValue == true` but `new Option(default(object)).HasValue == false`, which may make `Option` class less obvious... 
I realize the intention to void `new Option(null).HasValue` been `true`, but just thinking - what if this is a feature, not a bug? Besides, this may become a pretty tricky breaking change...

Just need to think twice before merging this change I think.

Comment (Arkatufus) [reply src/core/Akka/Util/Option.cs:33]: BTW, the scala implementation actually throws a `NoSuchElementException` if you try to access a null value, which i think the right implementation... but changing that would probably break binary compatibility

Comment (Arkatufus) [reply src/core/Akka/Util/Option.cs:33]: Our implementation is flawed anyway, Option<T> is supposed to be an IOption<T> with Some<T> and None<T> concrete classes

Comment (IgorFedchenko) [reply src/core/Akka/Util/Option.cs:33]: Yeah, I agree with all of that, just thinking about how many things we can break because people are passing null (and how often they are doing this by design)

Comment (Arkatufus) [reply src/core/Akka/Util/Option.cs:33]: No idea, its broken from the start

Comment (Arkatufus) [reply src/core/Akka/Util/Option.cs:33]: Yeah, it even broke our own code.
This is stupid, I feel like I'm chasing my own tail.

Comment (IgorFedchenko) [reply src/core/Akka/Util/Option.cs:33]: This is a good fix actually, I would love to see exception thrown here too - but maybe this should be done on some breaking change release, i.e. Akka.NET 1.5, or even 2.0, because chances are that many users will need to debug their app and fix things.

Comment (Arkatufus) [reply src/core/Akka/Util/Option.cs:33]: I think the proper thing to do right now is to implement the right `IOption<T>` interface but make it internal and keep the old `Option<T>` struct for public consumption.
But this will require so so many work to convert every `Option<T>` in our code x__x

Comment (Aaronontheweb) [reply src/core/Akka/Util/Option.cs:33]: Why do we need the `IOption<T>` interface exactly? I get the `Some<T>` and `None<T>`

**Review by Aaronontheweb — COMMENTED** [review]
Left some comments

**Comment by Arkatufus** [comment]
We needed `IOption<T>` to simulate the scala implementation to the T, it would make Option unambiguous, a None is always a None and a Some will always contain something, it makes it save to do a typed switch on the type of the returned value.

We don't need it per se, but by implementing it we can separate the internal implementation of Option with the one that is being used by user, just in case changing Option will break someone elses code. Pretty much a bandaid with backward compatibility.

**Comment by Arkatufus** [comment]
But it will be a very big bandaid, akin to using a nuclear warhead to kill an ant.

**Comment by Arkatufus** [comment]
The big fear right now is that, even changing that line in `Option` might break someone elses code.
It already break ours, we're also (ab)using `Option` as a tri-state return value inside the `Collect` stream dsl.

**Comment by Aaronontheweb** [comment]
As long as:

1. It doesn't take long to implement;
2. Doesn't introduce additional complexities / issues in terms of API compatibility; and
3. Doesn't introduce lots of new allocations.

Then I think we should do it "the right way"

**Comment by Arkatufus** [comment]
1. Yes, it will take awhile to implement.
2. We can change it as carefully as possible so that it doesn't change the public API
3. It will probably have some memory impact.

**Comment by Arkatufus** [comment]
Memory impact will most probably came from stack allocation, I think struct was chosen exactly because of this.

**Comment by Aaronontheweb** [comment]
> Memory impact will most probably came from stack allocation, I think struct was chosen exactly because of this.

that's fine then

**Comment by Aaronontheweb** [comment]
as long as we don't allocate on every `Option.[name of read method]`
