### PR TITLE
Fix `Akka.Util.Result` edge case

### LINKED ISSUE #7432: Stream upstream error propagation can fail in async calls
**Version Information**
Version of Akka.NET? Latest dev branch
Which Akka.NET Modules? Akka.Stream

**Describe the bug**

Related code:
https://github.com/akkadotnet/akka.net/blob/61bdebf6b9d24f858a2aa42263fe08e4ed62784d/src/core/Akka.Streams/Implementation/Fusing/Ops.cs#L2591-L2592

A bug in `Result<T>.FromTask()` where it failed to check for an edge case where a `Task` can be in a cancelled state but have its `Task.Exception` property be null. In fact, `TaskCancelledException` would only be thrown if `Task.Result` was called.

* This causes an event where `Result<T>` is in a failed state with its `Result<T>.Exception` property null. 
* This in turn is picked up by the upstream error propagation and 
* the null exception is passed upstream and was caught by the `OutGraphStageLogic.OnDownstreamFinish()` method, causing it to throw an `ArgumentException`. 
* This causes the whole stream to shutdown immediately without completing the proper graceful shutdown logic

Any code listening to the stream completion will never receive the completion signal. 
This can be the root cause of why Akka.Streams.Kafka fails, because the parent stream could not pick up the death of its sub-stream

**To Reproduce**

```csharp
var tcs = new TaskCompletionSource<int>();
tcs.TrySetCanceled();

var result = Result.FromTask(tcs.Task);
result.IsSuccess.Should().BeFalse();
result.Exception.Should().NotBeNull(); // Fails
```

### PR DESCRIPTION
**Pull request by Arkatufus**
Fixes #7432

## Changes

* Make sure that `Akka.Util.Result<T>.FromTask()` checks for edge cases
* Change `Akka.Util.Result<T>.FromTask()` behavior, it will now throw if the `Task` argument is not completed.

## Checklist

For significant changes, please ensure that the following have been completed (delete if not relevant):

* [x] This change follows the [Akka.NET API Compatibility Guidelines](https://getakka.net/community/contributing/api-changes-compatibility.html).
* [x] This change follows the [Akka.NET Wire Compatibility Guidelines](https://getakka.net/community/contributing/wire-compatibility.html).
* [x] I have [reviewed my own pull request](https://getakka.net/community/contributing/index.html#review-your-own-pull-requests).
* [x] Design discussion issue #7432

### CODE REVIEW

File: src/core/Akka/Util/Result.cs [hunk 1]
```diff
@@ -137,7 +137,30 @@ public static Result<T> Failure<T>(Exception exception)
...
+                {
+                    _ = task.GetAwaiter().GetResult();
+                }
+                catch(Exception e)
+                {
+                    return new Result<T>(e);
+                }
+
+                throw new InvalidOperationException("Should never reach this line!");
+            }
```
Comment (Arkatufus) [inline src/core/Akka/Util/Result.cs:158]: Fix, detect edge case where a `Task` is cancelled and its `Exception` property is null.

**Review by Arkatufus — COMMENTED** [review]
Self-review

File: src/core/Akka/Util/Result.cs [hunk 2]
```diff
@@ -137,7 +137,30 @@ public static Result<T> Failure<T>(Exception exception)
         /// <returns>TBD</returns>
         public static Result<T> FromTask<T>(Task<T> task)
         {
-            return task.IsCanceled || task.IsFaulted ? new Result<T>(task.Exception) : new Result<T>(task.Result);
+            if(!task.IsCompleted)
+                throw new ArgumentException("Task is not completed. Result.FromTask only accepts completed tasks.", nameof(task));
```
Comment (Arkatufus) [inline src/core/Akka/Util/Result.cs:141]: New behavior, `.FromTask()` did not check if the `Task` argument is completed or not, it should only accept completed tasks

**Review by Arkatufus — COMMENTED** [review]
Self-review

File: src/core/Akka/Util/Result.cs (hunk 1 above)
Comment (Aaronontheweb) [reply src/core/Akka/Util/Result.cs:158]: LGTM

**Review by Aaronontheweb — APPROVED** [review]
LGTM
