### PR TITLE
Fix leaky coordinated shutdown

### LINKED ISSUE #5802: ActorSystem leaks memory
**Version Information**
1.4.6 - 1.4.35
Did not test every single version but at least 1.4.6 and 1.4.35 leaks.
No leak on 1.4.5

.NET 6

Using Akka NuGet package

**Describe the bug**
Creating ActorSystem, terminating it and disposing it in a loop, leaves memory behind.

**To Reproduce**

Complete console app code example:
```
using Akka.Actor;

while (true)
{
    var actorSystem = ActorSystem.Create("test");

    await actorSystem.Terminate();
    actorSystem.Dispose();
    actorSystem = null;

    GC.Collect();
    GC.WaitForPendingFinalizers();
    GC.Collect();
}
```

Look at Visual Studio diagnostics memory usage or publish the app and look at memory usage in task manager. It will rise continously.

**Expected behavior**
Memory usage should flatline and not keep rising.

**Actual behavior**
Memory usage kept rising and did not stop like in 1.4.5.

**Screenshots**
1.4.35 memory usage graph: https://imgur.com/qJgGHFw
1.4.5 memory usage graph: https://imgur.com/ggyhBrc
1.4.35 memory usage snapshot diff: https://imgur.com/Mhdlwpc

**Environment**
Windows 10
.NET 6

**Additional context**

### PR DESCRIPTION
**Pull request by Arkatufus**
Fixes #5802

## Changes

* Fix possible infinite loop 
* Fix circular reference memory leak

### CODE REVIEW

File: src/core/Akka/Actor/CoordinatedShutdown.cs [hunk 1]
```diff
@@ -653,13 +653,15 @@ internal static void InitPhaseActorSystemTerminate(ActorSystem system, Config co
 
                     if (terminateActorSystem)
                     {
-                        system.FinalTerminate();
-                        return system.Terminate().ContinueWith(tr =>
```
Comment (Arkatufus) [inline src/core/Akka/Actor/CoordinatedShutdown.cs:657]: This potentially an infinite loop call, if the call came from `ActorSystem.Terminate()` in the first place.

File: src/core/Akka/Actor/CoordinatedShutdown.cs [hunk 2]
```diff
@@ -653,13 +653,15 @@ internal static void InitPhaseActorSystemTerminate(ActorSystem system, Config co
...
+                        return system.FinalTerminate().ContinueWith(tr =>
                         {
                             if (exitClr && !coord._runningClrHook)
                             {
                                 Environment.Exit(0);
                             }
+
+                            coord.System = null;
```
Comment (Arkatufus) [inline src/core/Akka/Actor/CoordinatedShutdown.cs:663]: Clear the reference to the `ActorSystem` to prevent a circular reference, preventing the `ActorSystem` from being garbage collected afterward.

**Review by Aaronontheweb — APPROVED** [review]
LGTM - need to see if CI digs up anything harmful here with the changing of the `CoordinatedShutdown` tasks though

**Comment by Arkatufus** [comment]
dotMemory profiling of 500 consecutive creation and termination of a single `ActorSystem`.

### Before

image

### After

image

**Comment by Aaronontheweb** [comment]
Nice work, definitely looks like it solved the memory issue.

**Comment by isurakka** [comment]
Hey, I'm still able to reproduce the leak with this code:

```
using Akka.Actor;

while (true)
{
    var actorSystem = ActorSystem.Create("test");

    await actorSystem.Terminate();
    actorSystem.Dispose();
    actorSystem = null;

    GC.Collect();
    GC.WaitForPendingFinalizers();
    GC.Collect();
}
```

**Comment by Arkatufus** [comment]
@isurakka 
Are you using a custom build of Akka using this new PR?
This fix is still not in effect, we still need to have this merged in and included in a release.

**Comment by Arkatufus** [comment]
OK, this should really fix it.
[](https://user-images.githubusercontent.com/8293237/161600051-b46d110c-10af-4a09-8f32-989e44de5a6a.png)Found the real culprit, CoordinatedShutdown._clrShutdownTasks is a ConcurrentBag, ConcurrentBag uses ThreadLocal, ThreadLocal acts like a static inside the thread and never get GC-ed.

CoordinatedShutdown+<>c_DisplayClass55_0 is a compiler generated EventHandler function for the CoordinatedShutdown.InitClrHook method.
image

Memory allocation after the fix:
image

File: src/core/Akka/Actor/CoordinatedShutdown.cs [hunk 3]
```diff
@@ -270,7 +270,7 @@ public class ClusterJoinUnsuccessfulReason : Reason
         /// </summary>
         internal readonly List<string> OrderedPhases;
 
-        private readonly ConcurrentBag<Func<Task<Done>>> _clrShutdownTasks = new ConcurrentBag<Func<Task<Done>>>();
```
Comment (Arkatufus) [inline src/core/Akka/Actor/CoordinatedShutdown.cs:273]: This is the real cause of the memory leak. `ConcurrentBag` uses `ThreadLocal` that pinned the lambdas in memory, preventing them from being GC-ed.

File: src/core/Akka/Actor/CoordinatedShutdown.cs [hunk 4]
```diff
@@ -691,7 +694,11 @@ internal static void InitClrHook(ActorSystem system, Config conf, CoordinatedShu
                 var exitTask = TerminateOnClrExit(coord);
                 // run all hooks during termination sequence
                 AppDomain.CurrentDomain.ProcessExit += exitTask;
-                system.WhenTerminated.ContinueWith(tr => { AppDomain.CurrentDomain.ProcessExit -= exitTask; });
+                system.WhenTerminated.ContinueWith(tr =>
+                {
+                    AppDomain.CurrentDomain.ProcessExit -= exitTask;
+                    coord._clrShutdownTasks.Clear(); // Clear the tasks, just in case it is retained in memory
```
Comment (Arkatufus) [inline src/core/Akka/Actor/CoordinatedShutdown.cs:700]: I'm pretty sure that `ConcurrentSet` does not use `ThreadLocal`, but lets add this just in case that changes in the future.

**Comment by Arkatufus** [comment]
This is the code I use to test for the memory leak, you will need JetBrains dotMemory and add the `JetBrains.Profiler.SelfApi` nuget package:
```c#
using Akka.Actor;
using Akka.Configuration;
using JetBrains.Profiler.SelfApi;

Console.WriteLine("Downloading DotMemory...");
await DotMemory.EnsurePrerequisiteAsync();
Console.WriteLine("Download complete.");

var profileConfig = new DotMemory.Config()
    .SaveToDir("./TestResults/")
    .OpenDotMemory();
DotMemory.Attach(profileConfig);

var config = ConfigurationFactory.ParseString(@"
akka.coordinated-shutdown.run-by-actor-system-terminate = on
akka.coordinated-shutdown.run-by-clr-shutdown-hook = on
");

Console.WriteLine("Grabbing 1st snapshot");
DotMemory.GetSnapshot();
Console.WriteLine("Starting loop");
try
{
    for (var i = 0; i < 100; ++i)
    {
        Console.WriteLine(i);
        var actorSystem = ActorSystem.Create("test", config);
        await actorSystem.Terminate();
    }
    await Task.Delay(1000);
    GC.Collect();
    GC.WaitForPendingFinalizers();
    GC.Collect();
    await Task.Delay(1000);
    Console.WriteLine("Grabbing 2nd snapshot");
    DotMemory.GetSnapshot();
}
finally
{
    DotMemory.Detach();
}
Console.WriteLine("Profiling done.");
```

File: src/core/Akka/Actor/CoordinatedShutdown.cs (hunk 3 above)
Comment (Aaronontheweb) [reply src/core/Akka/Actor/CoordinatedShutdown.cs:273]: yikes

**Review by Aaronontheweb — APPROVED** [review]
LGTM
