### PR TITLE
Throw clearer error message during `Stash()` in `null` message cases

### LINKED ISSUE #7398: Misleading error text when IllegalActorStateException is raised on attemp to stash a lifecycle message
**Version Information**
Version 1.5.31

**Describe the bug**
If an actor tries to stash a lifecycle message (e.g. **PreStart**), the **IllegalActorStateException** is raised with the text "Can't stash the same message  more than once". The text is supposed to include the actual message, but in case of PreStart current message is **null**, so no message information is included in the text. This is confusing because there is no attempt to stash a message twice, there is an attempt to stash a message that can't be stashed. 

**Expected behavior**
Either **InvalidOperationException** should be raised, or the text for **IllegalActorStateException** should state that such message can't be stashed.

**Actual behavior**
**IllegalActorStateException** is raised with the text "Can't stash the same message  more than once".

**Additional context**
In case a lifecycle message is being stashed, the **currMessage** is **null**, and both **_currentEnvelopeId** and **_actorCell.CurrentEnvelopeId** are **zero** (their equality triggers the exception). So there should be a check for nullable currMessage that should trigger either better exception text or **InvalidOperationException**.

### PR DESCRIPTION
**Pull request by Aaronontheweb**
## Changes

close #7398 

## Checklist

For significant changes, please ensure that the following have been completed (delete if not relevant):

* [x] This change follows the [Akka.NET API Compatibility Guidelines](https://getakka.net/community/contributing/api-changes-compatibility.html).
* [x] This change follows the [Akka.NET Wire Compatibility Guidelines](https://getakka.net/community/contributing/wire-compatibility.html).
* [x] I have [reviewed my own pull request](https://getakka.net/community/contributing/index.html#review-your-own-pull-requests).
* [x] Design discussion issue #7398

### CODE REVIEW

File: src/core/Akka/Actor/Stash/Internal/AbstractStash.cs [hunk 1]
```diff
@@ -74,9 +74,11 @@ public void Stash()
         {
             var currMsg = _actorCell.CurrentMessage;
             var sender = _actorCell.Sender;
-
+            
             if (_actorCell.CurrentEnvelopeId == _currentEnvelopeId)
             {
+                if(currMsg is null)
+                    throw new InvalidOperationException("There is no message to stash right now. Stash() must be called inside an actor's Receive methods.");
```
Comment (Aaronontheweb) [inline src/core/Akka/Actor/Stash/Internal/AbstractStash.cs:81]: Provide a clearer explanation of why we're throwing an exception

**Review by Aaronontheweb — COMMENTED** [review]
Detailed my changes
